input("cpsf:DataSemantics","cpsf:includesConcern","cpsf:Meaning").
input("cpsf:DataSemantics","cpsf:includesConcern","cpsf:Granularity").
input("cpsf:DataSemantics","cpsf:includesConcern","cpsf:DataModels").
input("cpsf:DataSemantics","rdf:type","cpsf:Concern").
input("cpsf:DataSemantics","rdf:type","owl:NamedIndividual").
input("cpsf:Manageability","rdf:type","cpsf:Concern").
input("cpsf:Manageability","rdf:type","owl:NamedIndividual").
input("cpsf:Procureability","rdf:type","cpsf:Concern").
input("cpsf:Procureability","rdf:type","owl:NamedIndividual").
input("cpsf:Engineerability","rdf:type","cpsf:Concern").
input("cpsf:Engineerability","rdf:type","owl:NamedIndividual").
input("cpsf:Verification","rdf:type","cpsf:Concern").
input("cpsf:Verification","rdf:type","owl:NamedIndividual").
input("cpsf:HumanFactors","rdf:type","cpsf:Concern").
input("cpsf:HumanFactors","rdf:type","owl:NamedIndividual").
input("cpsf:Cost","rdf:type","cpsf:Concern").
input("cpsf:Cost","rdf:type","owl:NamedIndividual").
input("cpsf:ir0002","rdfs:comment","cpsf:Integrity is addressed by property cpsf:Input1SecBoot").
input("cpsf:ir0002","cpsf:hasCondition","cpsf:c0002_01").
input("cpsf:ir0002","cpsf:addressesPolarity","cpsf:positive").
input("cpsf:ir0002","cpsf:addressesConcern","cpsf:Integrity").
input("cpsf:ir0002","cpsf:addressesAtFunc","cpsf:bc1").
input("cpsf:ir0002","rdf:type","cpsf:ImpactRule").
input("cpsf:ir0002","rdf:type","owl:NamedIndividual").
input("cpsf:conditionProperty","rdfs:comment","pg 15").
input("cpsf:conditionProperty","rdfs:comment","CPS-specific").
input("cpsf:conditionProperty","rdfs:range","cpsf:Property").
input("cpsf:conditionProperty","rdfs:domain","cpsf:Condition").
input("cpsf:conditionProperty","rdf:type","owl:ObjectProperty").
input("cpsf:RealizationFacet","rdfs:comment","CPS-independent").
input("cpsf:RealizationFacet","rdf:type","cpsf:Facet").
input("cpsf:RealizationFacet","rdf:type","owl:NamedIndividual").
input("cpsf:Communication","rdf:type","cpsf:Concern").
input("cpsf:Communication","rdf:type","owl:NamedIndividual").
input("cpsf:OperationsOnData","cpsf:includesConcern","cpsf:Transformation").
input("cpsf:OperationsOnData","cpsf:includesConcern","cpsf:Storage").
input("cpsf:OperationsOnData","cpsf:includesConcern","cpsf:Fusion").
input("cpsf:OperationsOnData","cpsf:includesConcern","cpsf:Analytics").
input("cpsf:OperationsOnData","cpsf:includesConcern","cpsf:Aggregation_Disaggregation").
input("cpsf:OperationsOnData","rdf:type","cpsf:Concern").
input("cpsf:OperationsOnData","rdf:type","owl:NamedIndividual").
input("cpsf:TimeAwareness","rdf:type","cpsf:Concern").
input("cpsf:TimeAwareness","rdf:type","owl:NamedIndividual").
input("cpsf:Business","rdf:type","owl:NamedIndividual").
input("cpsf:Business","cpsf:includesConcern","cpsf:Planning").
input("cpsf:Business","cpsf:includesConcern","cpsf:Enterprise").
input("cpsf:Business","cpsf:includesConcern","cpsf:TimeToMarket").
input("cpsf:Business","cpsf:includesConcern","cpsf:Regulatory").
input("cpsf:Business","rdf:type","cpsf:Aspect").
input("cpsf:Business","cpsf:includesConcern","cpsf:Quality").
input("cpsf:Business","cpsf:includesConcern","cpsf:Cost").
input("cpsf:Business","cpsf:includesConcern","cpsf:Environment").
input("cpsf:Business","cpsf:includesConcern","cpsf:Policy").
input("cpsf:Business","cpsf:includesConcern","cpsf:Utility").
input("cpsf:Environment","rdf:type","cpsf:Concern").
input("cpsf:Environment","rdf:type","owl:NamedIndividual").
input("cpsf:refinedInto","rdfs:range","cpsf:Function").
input("cpsf:refinedInto","rdfs:domain","cpsf:Function").
input("cpsf:refinedInto","rdf:type","owl:ObjectProperty").
input("cpsf:Integrity","cpsf:relevantToFunc","cpsf:bc1").
input("cpsf:Integrity","rdf:type","cpsf:Concern").
input("cpsf:Integrity","rdf:type","owl:NamedIndividual").
input("cpsf:Measurability","rdf:type","cpsf:Concern").
input("cpsf:Measurability","rdf:type","owl:NamedIndividual").
input("cpsf:Discoverability","rdf:type","cpsf:Concern").
input("cpsf:Discoverability","rdf:type","owl:NamedIndividual").
input("cpsf:Function","rdfs:subClassOf","cpsf:CPSFrameworkConcept").
input("cpsf:Function","rdf:type","owl:Class").
input("cpsf:addressesPolarity","rdfs:range","cpsf:ImpactPolarity").
input("cpsf:addressesPolarity","rdfs:domain","cpsf:ImpactRule").
input("cpsf:addressesPolarity","rdf:type","owl:ObjectProperty").
input("cpsf:SAMEncryptedMem","rdfs:comment","SAM uses encrypted memory").
input("cpsf:SAMEncryptedMem","cpsf:atomicStatement","encrypted_mem_sam").
input("cpsf:SAMEncryptedMem","cpsf:hasType","cpsf:PropertyType_Assertion").
input("cpsf:SAMEncryptedMem","rdf:type","cpsf:Property").
input("cpsf:SAMEncryptedMem","rdf:type","owl:NamedIndividual").
input("cpsf:Input1SecBoot","rdfs:comment","The sensor array uses secure boot").
input("cpsf:Input1SecBoot","cpsf:atomicStatement","sec_boot_input1").
input("cpsf:Input1SecBoot","cpsf:hasType","cpsf:PropertyType_Assertion").
input("cpsf:Input1SecBoot","rdf:type","cpsf:Property").
input("cpsf:Input1SecBoot","rdf:type","owl:NamedIndividual").
input("cpsf:positive","rdf:type","cpsf:ImpactPolarity").
input("cpsf:positive","rdf:type","owl:NamedIndividual").
input("cpsf:DeviceIdentification","rdf:type","cpsf:Concern").
input("cpsf:DeviceIdentification","rdf:type","owl:NamedIndividual").
input("cpsf:Analytics","rdf:type","cpsf:Concern").
input("cpsf:Analytics","rdf:type","owl:NamedIndividual").
input("cpsf:c0005_01","cpsf:conditionProperty","cpsf:SAMEncryptedMem").
input("cpsf:c0005_01","cpsf:conditionPolarity","cpsf:positive").
input("cpsf:c0005_01","rdf:type","cpsf:Condition").
input("cpsf:c0005_01","rdf:type","owl:NamedIndividual").
input("cpsf:RelatedData","rdf:type","cpsf:Concern").
input("cpsf:RelatedData","rdf:type","owl:NamedIndividual").
input("cpsf:ir0005","rdfs:comment","cpsf:Confidentiality is addressed by property cpsf:SAMEncryptedMem").
input("cpsf:ir0005","cpsf:hasCondition","cpsf:c0005_01").
input("cpsf:ir0005","cpsf:addressesPolarity","cpsf:positive").
input("cpsf:ir0005","cpsf:addressesConcern","cpsf:Confidentiality").
input("cpsf:ir0005","cpsf:addressesAtFunc","cpsf:bc1").
input("cpsf:ir0005","rdf:type","cpsf:ImpactRule").
input("cpsf:ir0005","rdf:type","owl:NamedIndividual").
input("cpsf:Meaning","rdf:type","cpsf:Concern").
input("cpsf:Meaning","rdf:type","owl:NamedIndividual").
input("cpsf:atomicStatement","rdf:type","owl:DatatypeProperty").
input("cpsf:Authentication","rdf:type","cpsf:Concern").
input("cpsf:Authentication","rdf:type","owl:NamedIndividual").
input("cpsf:DataQuality","rdf:type","cpsf:Concern").
input("cpsf:DataQuality","rdf:type","owl:NamedIndividual").
input("cpsf:Property","rdfs:comment","pg 15").
input("cpsf:Property","rdfs:subClassOf","cpsf:CPSFrameworkConcept").
input("cpsf:Property","rdf:type","owl:Class").
input("cpsf:c0002_01","cpsf:conditionProperty","cpsf:Input1SecBoot").
input("cpsf:c0002_01","cpsf:conditionPolarity","cpsf:positive").
input("cpsf:c0002_01","rdf:type","cpsf:Condition").
input("cpsf:c0002_01","rdf:type","owl:NamedIndividual").
input("cpsf:Reliability","rdf:type","cpsf:Concern").
input("cpsf:Reliability","rdf:type","owl:NamedIndividual").
input("cpsf:Artifact","rdfs:subClassOf","cpsf:CPSFrameworkConcept").
input("cpsf:Artifact","rdf:type","owl:Class").
input("cpsf:hasBC","rdfs:range","cpsf:BusinessCase").
input("cpsf:hasBC","rdfs:domain","cpsf:Application").
input("cpsf:hasBC","rdfs:subPropertyOf","owl:topObjectProperty").
input("cpsf:hasBC","rdf:type","owl:ObjectProperty").
input("cpsf:BusinessCase","cpsf:nextFC","cpsf:UseCase").
input("cpsf:BusinessCase","rdf:type","cpsf:BusinessCase").
input("cpsf:BusinessCase","rdf:type","owl:NamedIndividual").
input("cpsf:BusinessCase","rdfs:subClassOf","cpsf:Function").
input("cpsf:BusinessCase","rdf:type","owl:Class").
input("cpsf:Synchronization","rdf:type","cpsf:Concern").
input("cpsf:Synchronization","rdf:type","owl:NamedIndividual").
input("cpsf:TimeIntervalAndLatencyControl","rdf:type","cpsf:Concern").
input("cpsf:TimeIntervalAndLatencyControl","rdf:type","owl:NamedIndividual").
input("cpsf:Safety","rdf:type","cpsf:Concern").
input("cpsf:Safety","rdf:type","owl:NamedIndividual").
input("cpsf:Privacy","rdf:type","cpsf:Concern").
input("cpsf:Privacy","rdf:type","owl:NamedIndividual").
input("cpsf:ConfigurationForLeastFFunctionality","rdf:type","cpsf:Concern").
input("cpsf:ConfigurationForLeastFFunctionality","rdf:type","owl:NamedIndividual").
input("cpsf:Complexity","rdf:type","cpsf:Concern").
input("cpsf:Complexity","rdf:type","owl:NamedIndividual").
input("cpsf:Actuation","rdf:type","cpsf:Concern").
input("cpsf:Actuation","rdf:type","owl:NamedIndividual").
input("cpsf:Confidentiality","cpsf:relevantToFunc","cpsf:bc1").
input("cpsf:Confidentiality","rdf:type","cpsf:Concern").
input("cpsf:Confidentiality","rdf:type","owl:NamedIndividual").
input("cpsf:uc1","rdf:type","cpsf:UseCase").
input("cpsf:uc1","rdf:type","owl:NamedIndividual").
input("cpsf:ManagingTimingAndLatency","rdf:type","cpsf:Concern").
input("cpsf:ManagingTimingAndLatency","rdf:type","owl:NamedIndividual").
input("cpsf:Usability","rdf:type","cpsf:Concern").
input("cpsf:Usability","rdf:type","owl:NamedIndividual").
input("cpsf:TimeOfData","rdf:type","cpsf:Concern").
input("cpsf:TimeOfData","rdf:type","owl:NamedIndividual").
input("cpsf:Producibility","rdf:type","cpsf:Concern").
input("cpsf:Producibility","rdf:type","owl:NamedIndividual").
input("cpsf:Planning","rdf:type","cpsf:Concern").
input("cpsf:Planning","rdf:type","owl:NamedIndividual").
input("cpsf:hasCondition","rdfs:comment","pg 15").
input("cpsf:hasCondition","rdfs:comment","CPS-specific").
input("cpsf:hasCondition","rdfs:range","cpsf:Condition").
input("cpsf:hasCondition","rdfs:domain","cpsf:ImpactRule").
input("cpsf:hasCondition","rdf:type","owl:ObjectProperty").
input("cpsf:Configuration","rdf:type","cpsf:Concern").
input("cpsf:Configuration","rdf:type","owl:NamedIndividual").
input("cpsf:DesignElement","rdfs:subClassOf","cpsf:Property").
input("cpsf:DesignElement","rdf:type","owl:Class").
input("cpsf:StatesAndModes","rdf:type","cpsf:Concern").
input("cpsf:StatesAndModes","rdf:type","owl:NamedIndividual").
input("cpsf:Aggregation_Disaggregation","rdf:type","cpsf:Concern").
input("cpsf:Aggregation_Disaggregation","rdf:type","owl:NamedIndividual").
input("cpsf:Test","rdfs:subClassOf","cpsf:Property").
input("cpsf:Test","rdf:type","owl:Class").
input("cpsf:Scenario","rdf:type","cpsf:Scenario").
input("cpsf:Scenario","rdf:type","owl:NamedIndividual").
input("cpsf:Scenario","rdfs:subClassOf","cpsf:Function").
input("cpsf:Scenario","rdf:type","owl:Class").
input("cpsf:Activity","rdfs:subClassOf","cpsf:CPSFrameworkConcept").
input("cpsf:Activity","rdf:type","owl:Class").
input("cpsf:ConceptualizationFacet","rdfs:comment","CPS-independent").
input("cpsf:ConceptualizationFacet","rdf:type","cpsf:Facet").
input("cpsf:ConceptualizationFacet","rdf:type","owl:NamedIndividual").
input("cpsf:ImpactRule","rdfs:subClassOf","cpsf:ImpactRuleConcepts").
input("cpsf:ImpactRule","rdf:type","owl:Class").
input("cpsf:ir0003","rdfs:comment","cpsf:Functionality is addressed by property cpsf:Input1ConsistentReadingFreq").
input("cpsf:ir0003","cpsf:hasCondition","cpsf:c0003_01").
input("cpsf:ir0003","cpsf:addressesPolarity","cpsf:positive").
input("cpsf:ir0003","cpsf:addressesConcern","cpsf:Functionality").
input("cpsf:ir0003","cpsf:addressesAtFunc","cpsf:bc1").
input("cpsf:ir0003","rdf:type","cpsf:ImpactRule").
input("cpsf:ir0003","rdf:type","owl:NamedIndividual").
input("cpsf:relevantToFunc","rdfs:range","cpsf:Function").
input("cpsf:relevantToFunc","rdfs:domain","cpsf:Concern").
input("cpsf:relevantToFunc","rdf:type","owl:ObjectProperty").
input("<http://www.asklab.tk/ontologies/CPS-Framework>","rdf:type","owl:Ontology").
input("cpsf:Sensing","rdf:type","cpsf:Concern").
input("cpsf:Sensing","rdf:type","owl:NamedIndividual").
input("cpsf:Deployability","rdf:type","cpsf:Concern").
input("cpsf:Deployability","rdf:type","owl:NamedIndividual").
input("cpsf:PhysicalSecurity","rdf:type","cpsf:Concern").
input("cpsf:PhysicalSecurity","rdf:type","owl:NamedIndividual").
input("cpsf:Monitorability","rdf:type","cpsf:Concern").
input("cpsf:Monitorability","rdf:type","owl:NamedIndividual").
input("cpsf:Provenance","rdf:type","cpsf:Concern").
input("cpsf:Provenance","rdf:type","owl:NamedIndividual").
input("cpsf:Resilience","rdf:type","cpsf:Concern").
input("cpsf:Resilience","rdf:type","owl:NamedIndividual").
input("cpsf:Functionality","cpsf:relevantToFunc","cpsf:bc1").
input("cpsf:Functionality","rdf:type","cpsf:Concern").
input("cpsf:Functionality","rdf:type","owl:NamedIndividual").
input("cpsf:Timing","cpsf:includesConcern","cpsf:TimeIntervalAndLatencyControl").
input("cpsf:Timing","cpsf:includesConcern","cpsf:TimeAwareness").
input("cpsf:Timing","cpsf:includesConcern","cpsf:Synchronization").
input("cpsf:Timing","cpsf:includesConcern","cpsf:ManagingTimingAndLatency").
input("cpsf:Timing","cpsf:includesConcern","cpsf:LogicalTime").
input("cpsf:Timing","rdf:type","cpsf:Aspect").
input("cpsf:Timing","rdf:type","owl:NamedIndividual").
input("cpsf:c0004_01","cpsf:conditionProperty","cpsf:Input1Modes").
input("cpsf:c0004_01","cpsf:conditionPolarity","cpsf:positive").
input("cpsf:c0004_01","rdf:type","cpsf:Condition").
input("cpsf:c0004_01","rdf:type","owl:NamedIndividual").
input("cpsf:Requirement","rdfs:subClassOf","cpsf:Property").
input("cpsf:Requirement","rdf:type","owl:Class").
input("cpsf:Security","cpsf:includesConcern","cpsf:PhysicalSecurity").
input("cpsf:Security","cpsf:includesConcern","cpsf:Cybersecurity").
input("cpsf:Security","rdf:type","cpsf:Concern").
input("cpsf:Security","rdf:type","owl:NamedIndividual").
input("cpsf:includesArtifact","rdfs:comment","pg 16").
input("cpsf:includesArtifact","rdfs:comment","CPS-specific").
input("cpsf:includesArtifact","rdfs:range","cpsf:Artifact").
input("cpsf:includesArtifact","rdfs:domain","cpsf:Facet").
input("cpsf:includesArtifact","rdf:type","owl:ObjectProperty").
input("cpsf:Uncertainty","rdf:type","cpsf:Concern").
input("cpsf:Uncertainty","rdf:type","owl:NamedIndividual").
input("cpsf:PropertyType","rdfs:subClassOf","cpsf:CPSFrameworkConcept").
input("cpsf:PropertyType","rdf:type","owl:Class").
input("cpsf:LocationOfData","rdf:type","cpsf:Concern").
input("cpsf:LocationOfData","rdf:type","owl:NamedIndividual").
input("cpsf:Application","rdfs:subClassOf","cpsf:CPSFrameworkConcept").
input("cpsf:Application","rdf:type","owl:Class").
input("cpsf:ir0006","rdfs:comment","cpsf:Confidentiality is addressed by property cpsf:Input1EncryptedMem").
input("cpsf:ir0006","cpsf:hasCondition","cpsf:c0006_01").
input("cpsf:ir0006","cpsf:addressesPolarity","cpsf:positive").
input("cpsf:ir0006","cpsf:addressesConcern","cpsf:Confidentiality").
input("cpsf:ir0006","cpsf:addressesAtFunc","cpsf:bc1").
input("cpsf:ir0006","rdf:type","cpsf:ImpactRule").
input("cpsf:ir0006","rdf:type","owl:NamedIndividual").
input("cpsf:c0001_01","cpsf:conditionProperty","cpsf:SAMSecBoot").
input("cpsf:c0001_01","cpsf:conditionPolarity","cpsf:positive").
input("cpsf:c0001_01","rdf:type","cpsf:Condition").
input("cpsf:c0001_01","rdf:type","owl:NamedIndividual").
input("cpsf:Disposability","rdf:type","cpsf:Concern").
input("cpsf:Disposability","rdf:type","owl:NamedIndividual").
input("cpsf:ImpactRuleConcepts","rdfs:subClassOf","cpsf:CPSFrameworkConcept").
input("cpsf:ImpactRuleConcepts","rdf:type","owl:Class").
input("cpsf:ResourceIdentification","cpsf:includesConcern","cpsf:UserIdentification").
input("cpsf:ResourceIdentification","cpsf:includesConcern","cpsf:ObjectIdentification").
input("cpsf:ResourceIdentification","cpsf:includesConcern","cpsf:DeviceIdentification").
input("cpsf:ResourceIdentification","cpsf:includesConcern","cpsf:ClassIdentification").
input("cpsf:ResourceIdentification","rdf:type","cpsf:Concern").
input("cpsf:ResourceIdentification","rdf:type","owl:NamedIndividual").
input("cpsf:Polymorphism","rdf:type","cpsf:Concern").
input("cpsf:Polymorphism","rdf:type","owl:NamedIndividual").
input("cpsf:app1","cpsf:hasBC","cpsf:bc1").
input("cpsf:app1","rdf:type","cpsf:Application").
input("cpsf:app1","rdf:type","owl:NamedIndividual").
input("cpsf:TimeToMarket","rdf:type","cpsf:Concern").
input("cpsf:TimeToMarket","rdf:type","owl:NamedIndividual").
input("cpsf:Input1EncryptedMem","rdfs:comment","The sensor array uses encrypted memory").
input("cpsf:Input1EncryptedMem","cpsf:atomicStatement","encrypted_mem_input1").
input("cpsf:Input1EncryptedMem","cpsf:hasType","cpsf:PropertyType_Assertion").
input("cpsf:Input1EncryptedMem","rdf:type","cpsf:Property").
input("cpsf:Input1EncryptedMem","rdf:type","owl:NamedIndividual").
input("cpsf:Controllability","rdf:type","cpsf:Concern").
input("cpsf:Controllability","rdf:type","owl:NamedIndividual").
input("cpsf:PropertyType_Capability","rdf:type","cpsf:PropertyType").
input("cpsf:PropertyType_Capability","rdf:type","owl:NamedIndividual").
input("cpsf:addressesAtFunc","rdfs:range","cpsf:Function").
input("cpsf:addressesAtFunc","rdfs:domain","cpsf:ImpactRule").
input("cpsf:addressesAtFunc","rdf:type","owl:ObjectProperty").
input("cpsf:includesConcern","rdfs:comment","pg 15").
input("cpsf:includesConcern","rdfs:comment","CPS-independent").
input("cpsf:includesConcern","rdfs:range","cpsf:Concern").
input("cpsf:includesConcern","rdfs:domain","cpsf:Concern").
input("cpsf:includesConcern","rdf:type","owl:ObjectProperty").
input("cpsf:Composition","cpsf:includesConcern","cpsf:Discoverability").
input("cpsf:Composition","cpsf:includesConcern","cpsf:Constructivity").
input("cpsf:Composition","cpsf:includesConcern","cpsf:Complexity").
input("cpsf:Composition","cpsf:includesConcern","cpsf:Adaptability").
input("cpsf:Composition","rdf:type","cpsf:Aspect").
input("cpsf:Composition","rdf:type","owl:NamedIndividual").
input("cpsf:addressesConcern","rdfs:comment","pg 15").
input("cpsf:addressesConcern","rdfs:comment","CPS-specific").
input("cpsf:addressesConcern","rdfs:range","cpsf:Concern").
input("cpsf:addressesConcern","rdfs:domain","cpsf:ImpactRule").
input("cpsf:addressesConcern","rdf:type","owl:ObjectProperty").
input("cpsf:Concern","rdfs:comment","pg 15").
input("cpsf:Concern","rdfs:comment","all instances are CPS-independent").
input("cpsf:Concern","rdfs:subClassOf","cpsf:CPSFrameworkConcept").
input("cpsf:Concern","rdf:type","owl:Class").
input("cpsf:Quality","rdf:type","cpsf:Concern").
input("cpsf:Quality","rdf:type","owl:NamedIndividual").
input("cpsf:conditionPolarity","rdfs:range","cpsf:ImpactPolarity").
input("cpsf:conditionPolarity","rdfs:domain","cpsf:Condition").
input("cpsf:conditionPolarity","rdf:type","owl:ObjectProperty").
input("cpsf:ComponentInventory","rdf:type","cpsf:Concern").
input("cpsf:ComponentInventory","rdf:type","owl:NamedIndividual").
input("cpsf:Inheritance","rdf:type","cpsf:Concern").
input("cpsf:Inheritance","rdf:type","owl:NamedIndividual").
input("cpsf:Enterprise","rdf:type","cpsf:Concern").
input("cpsf:Enterprise","rdf:type","owl:NamedIndividual").
input("cpsf:Behavioral","rdf:type","cpsf:Concern").
input("cpsf:Behavioral","rdf:type","owl:NamedIndividual").
input("cpsf:Lifecycle","cpsf:includesConcern","cpsf:Producibility").
input("cpsf:Lifecycle","cpsf:includesConcern","cpsf:Procureability").
input("cpsf:Lifecycle","cpsf:includesConcern","cpsf:Operatability").
input("cpsf:Lifecycle","cpsf:includesConcern","cpsf:Maintainability").
input("cpsf:Lifecycle","cpsf:includesConcern","cpsf:Engineerability").
input("cpsf:Lifecycle","cpsf:includesConcern","cpsf:Disposability").
input("cpsf:Lifecycle","cpsf:includesConcern","cpsf:Deployability").
input("cpsf:Lifecycle","rdf:type","cpsf:Aspect").
input("cpsf:Lifecycle","rdf:type","owl:NamedIndividual").
input("cpsf:ir0001","rdfs:comment","cpsf:Integrity is addressed by property cpsf:SAMSecBoot").
input("cpsf:ir0001","cpsf:hasCondition","cpsf:c0001_01").
input("cpsf:ir0001","cpsf:addressesPolarity","cpsf:positive").
input("cpsf:ir0001","cpsf:addressesConcern","cpsf:Integrity").
input("cpsf:ir0001","cpsf:addressesAtFunc","cpsf:bc1").
input("cpsf:ir0001","rdf:type","cpsf:ImpactRule").
input("cpsf:ir0001","rdf:type","owl:NamedIndividual").
input("cpsf:ConfigurationManagement","rdf:type","cpsf:Concern").
input("cpsf:ConfigurationManagement","rdf:type","owl:NamedIndividual").
input("cpsf:uc2","rdf:type","cpsf:UseCase").
input("cpsf:uc2","rdf:type","owl:NamedIndividual").
input("cpsf:ImpactPolarity","rdfs:subClassOf","cpsf:ImpactRuleConcepts").
input("cpsf:ImpactPolarity","rdf:type","owl:Class").
input("cpsf:includesActivity","rdfs:comment","pg 16").
input("cpsf:includesActivity","rdfs:comment","CPS-specific").
input("cpsf:includesActivity","rdfs:range","cpsf:Activity").
input("cpsf:includesActivity","rdfs:domain","cpsf:Facet").
input("cpsf:includesActivity","rdf:type","owl:ObjectProperty").
input("cpsf:Maintainability","cpsf:includesConcern","cpsf:ConfigurationManagement").
input("cpsf:Maintainability","cpsf:includesConcern","cpsf:ConfigurationForLeastFFunctionality").
input("cpsf:Maintainability","cpsf:includesConcern","cpsf:ComponentInventory").
input("cpsf:Maintainability","rdf:type","cpsf:Concern").
input("cpsf:Maintainability","rdf:type","owl:NamedIndividual").
input("cpsf:DataModels","rdf:type","cpsf:Concern").
input("cpsf:DataModels","rdf:type","owl:NamedIndividual").
input("cpsf:hasType","rdfs:range","cpsf:PropertyType").
input("cpsf:hasType","rdfs:domain","cpsf:Property").
input("cpsf:hasType","rdf:type","owl:ObjectProperty").
input("cpsf:Trustworthiness","cpsf:includesConcern","cpsf:Security").
input("cpsf:Trustworthiness","cpsf:includesConcern","cpsf:Safety").
input("cpsf:Trustworthiness","cpsf:includesConcern","cpsf:Resilience").
input("cpsf:Trustworthiness","cpsf:includesConcern","cpsf:Reliability").
input("cpsf:Trustworthiness","cpsf:includesConcern","cpsf:Privacy").
input("cpsf:Trustworthiness","rdf:type","cpsf:Aspect").
input("cpsf:Trustworthiness","rdf:type","owl:NamedIndividual").
input("cpsf:Functional","cpsf:includesConcern","cpsf:Sensing").
input("cpsf:Functional","cpsf:includesConcern","cpsf:Measurability").
input("cpsf:Functional","cpsf:includesConcern","cpsf:Uncertainty").
input("cpsf:Functional","cpsf:includesConcern","cpsf:Manageability").
input("cpsf:Functional","cpsf:includesConcern","cpsf:StatesAndModes").
input("cpsf:Functional","cpsf:includesConcern","cpsf:Functionality").
input("cpsf:Functional","cpsf:includesConcern","cpsf:Communication").
input("cpsf:Functional","cpsf:includesConcern","cpsf:Performance").
input("cpsf:Functional","cpsf:includesConcern","cpsf:Controllability").
input("cpsf:Functional","cpsf:includesConcern","cpsf:Actuation").
input("cpsf:Functional","rdf:type","cpsf:Aspect").
input("cpsf:Functional","cpsf:includesConcern","cpsf:PhysicalContext").
input("cpsf:Functional","cpsf:includesConcern","cpsf:Monitorability").
input("cpsf:Functional","rdf:type","owl:NamedIndividual").
input("cpsf:Functional","cpsf:includesConcern","cpsf:Physical").
input("cpsf:Fusion","rdf:type","cpsf:Concern").
input("cpsf:Fusion","rdf:type","owl:NamedIndividual").
input("cpsf:PhysicalContext","rdf:type","cpsf:Concern").
input("cpsf:PhysicalContext","rdf:type","owl:NamedIndividual").
input("cpsf:Authorization","rdf:type","cpsf:Concern").
input("cpsf:Authorization","rdf:type","owl:NamedIndividual").
input("cpsf:Input1Modes","rdfs:comment","The sensor array should be capable of low-rate and of high-rate readings").
input("cpsf:Input1Modes","cpsf:atomicStatement","slow_mode_input1").
input("cpsf:Input1Modes","cpsf:hasType","cpsf:PropertyType_Capability").
input("cpsf:Input1Modes","rdf:type","cpsf:Property").
input("cpsf:Input1Modes","rdf:type","owl:NamedIndividual").
input("cpsf:Availability","rdf:type","cpsf:Concern").
input("cpsf:Availability","rdf:type","owl:NamedIndividual").
input("cpsf:ClassIdentification","rdf:type","cpsf:Concern").
input("cpsf:ClassIdentification","rdf:type","owl:NamedIndividual").
input("cpsf:Judgment","rdfs:subClassOf","cpsf:Property").
input("cpsf:Judgment","rdf:type","owl:Class").
input("cpsf:RelationshipBetweenData","cpsf:includesConcern","cpsf:TimeOfData").
input("cpsf:RelationshipBetweenData","cpsf:includesConcern","cpsf:RelatedData").
input("cpsf:RelationshipBetweenData","cpsf:includesConcern","cpsf:Polymorphism").
input("cpsf:RelationshipBetweenData","cpsf:includesConcern","cpsf:LocationOfData").
input("cpsf:RelationshipBetweenData","cpsf:includesConcern","cpsf:Inheritance").
input("cpsf:RelationshipBetweenData","cpsf:includesConcern","cpsf:DirectionalityOfRelationships").
input("cpsf:RelationshipBetweenData","cpsf:includesConcern","cpsf:DataQuality").
input("cpsf:RelationshipBetweenData","rdf:type","cpsf:Concern").
input("cpsf:RelationshipBetweenData","rdf:type","owl:NamedIndividual").
input("cpsf:LogicalTime","rdf:type","cpsf:Concern").
input("cpsf:LogicalTime","rdf:type","owl:NamedIndividual").
input("cpsf:ObjectIdentification","rdf:type","cpsf:Concern").
input("cpsf:ObjectIdentification","rdf:type","owl:NamedIndividual").
input("cpsf:Cybersecurity","cpsf:includesConcern","cpsf:Integrity").
input("cpsf:Cybersecurity","cpsf:includesConcern","cpsf:Confidentiality").
input("cpsf:Cybersecurity","cpsf:includesConcern","cpsf:Availability").
input("cpsf:Cybersecurity","rdf:type","cpsf:Concern").
input("cpsf:Cybersecurity","rdf:type","owl:NamedIndividual").
input("cpsf:UserIdentification","rdf:type","cpsf:Concern").
input("cpsf:UserIdentification","rdf:type","owl:NamedIndividual").
input("cpsf:CPSFrameworkConcept","rdf:type","owl:Class").
input("cpsf:Input1ConsistentReadingFreq","rdfs:comment","The sensor array returns accurate readings").
input("cpsf:Input1ConsistentReadingFreq","cpsf:atomicStatement","consist_reading_freq_input1").
input("cpsf:Input1ConsistentReadingFreq","cpsf:hasType","cpsf:PropertyType_Assertion").
input("cpsf:Input1ConsistentReadingFreq","rdf:type","cpsf:Property").
input("cpsf:Input1ConsistentReadingFreq","rdf:type","owl:NamedIndividual").
input("cpsf:PropertyType_Assertion","rdf:type","cpsf:PropertyType").
input("cpsf:PropertyType_Assertion","rdf:type","owl:NamedIndividual").
input("cpsf:Policy","rdf:type","cpsf:Concern").
input("cpsf:Policy","rdf:type","owl:NamedIndividual").
input("cpsf:ir0004","rdfs:comment","cpsf:TimeIntervalAndLatencyControl is addressed by property cpsf:Input1Modes").
input("cpsf:ir0004","cpsf:hasCondition","cpsf:c0004_01").
input("cpsf:ir0004","cpsf:addressesPolarity","cpsf:positive").
input("cpsf:ir0004","cpsf:addressesConcern","cpsf:TimeIntervalAndLatencyControl").
input("cpsf:ir0004","cpsf:addressesAtFunc","cpsf:bc1").
input("cpsf:ir0004","rdf:type","cpsf:ImpactRule").
input("cpsf:ir0004","rdf:type","owl:NamedIndividual").
input("cpsf:Facet","rdfs:comment","pg 16").
input("cpsf:Facet","rdfs:comment","all instances are CPS-independent").
input("cpsf:Facet","rdfs:subClassOf","cpsf:CPSFrameworkConcept").
input("cpsf:Facet","rdf:type","owl:Class").
input("cpsf:Operatability","rdf:type","cpsf:Concern").
input("cpsf:Operatability","rdf:type","owl:NamedIndividual").
input("cpsf:negative","rdf:type","cpsf:ImpactPolarity").
input("cpsf:negative","rdf:type","owl:NamedIndividual").
input("cpsf:Velocity","rdf:type","cpsf:Concern").
input("cpsf:Velocity","rdf:type","owl:NamedIndividual").
input("cpsf:c0006_01","cpsf:conditionProperty","cpsf:Input1EncryptedMem").
input("cpsf:c0006_01","cpsf:conditionPolarity","cpsf:positive").
input("cpsf:c0006_01","rdf:type","cpsf:Condition").
input("cpsf:c0006_01","rdf:type","owl:NamedIndividual").
input("cpsf:Utility","rdf:type","cpsf:Concern").
input("cpsf:Utility","rdf:type","owl:NamedIndividual").
input("cpsf:DirectionalityOfRelationships","rdf:type","cpsf:Concern").
input("cpsf:DirectionalityOfRelationships","rdf:type","owl:NamedIndividual").
input("cpsf:Human","cpsf:includesConcern","cpsf:Usability").
input("cpsf:Human","cpsf:includesConcern","cpsf:HumanFactors").
input("cpsf:Human","rdf:type","cpsf:Aspect").
input("cpsf:Human","rdf:type","owl:NamedIndividual").
input("cpsf:Performance","rdf:type","cpsf:Concern").
input("cpsf:Performance","rdf:type","owl:NamedIndividual").
input("cpsf:Boundaries","cpsf:includesConcern","cpsf:Responsibility").
input("cpsf:Boundaries","cpsf:includesConcern","cpsf:Networkability").
input("cpsf:Boundaries","cpsf:includesConcern","cpsf:Behavioral").
input("cpsf:Boundaries","rdf:type","cpsf:Aspect").
input("cpsf:Boundaries","rdf:type","owl:NamedIndividual").
input("cpsf:c0003_01","cpsf:conditionProperty","cpsf:Input1ConsistentReadingFreq").
input("cpsf:c0003_01","cpsf:conditionPolarity","cpsf:positive").
input("cpsf:c0003_01","rdf:type","cpsf:Condition").
input("cpsf:c0003_01","rdf:type","owl:NamedIndividual").
input("cpsf:Responsibility","rdf:type","cpsf:Concern").
input("cpsf:Responsibility","rdf:type","owl:NamedIndividual").
input("cpsf:bc1","cpsf:refinedInto","cpsf:uc2").
input("cpsf:bc1","cpsf:refinedInto","cpsf:uc1").
input("cpsf:bc1","rdf:type","cpsf:BusinessCase").
input("cpsf:bc1","rdf:type","owl:NamedIndividual").
input("cpsf:Granularity","rdf:type","cpsf:Concern").
input("cpsf:Granularity","rdf:type","owl:NamedIndividual").
input("cpsf:AssuranceFacet","rdfs:comment","CPS-independent").
input("cpsf:AssuranceFacet","rdf:type","cpsf:Facet").
input("cpsf:AssuranceFacet","rdf:type","owl:NamedIndividual").
input("cpsf:Transformation","rdf:type","cpsf:Concern").
input("cpsf:Transformation","rdf:type","owl:NamedIndividual").
input("cpsf:SAMSecBoot","rdfs:comment","SAM uses secure boot").
input("cpsf:SAMSecBoot","cpsf:atomicStatement","sec_boot_sam").
input("cpsf:SAMSecBoot","cpsf:hasType","cpsf:PropertyType_Assertion").
input("cpsf:SAMSecBoot","rdf:type","cpsf:Property").
input("cpsf:SAMSecBoot","rdf:type","owl:NamedIndividual").
input("cpsf:Regulatory","rdf:type","cpsf:Concern").
input("cpsf:Regulatory","rdf:type","owl:NamedIndividual").
input("cpsf:Aspect","rdfs:comment","pg 15").
input("cpsf:Aspect","rdfs:comment","all instances are CPS-independent").
input("cpsf:Aspect","rdfs:subClassOf","cpsf:Concern").
input("cpsf:Aspect","rdf:type","owl:Class").
input("cpsf:Networkability","rdf:type","cpsf:Concern").
input("cpsf:Networkability","rdf:type","owl:NamedIndividual").
input("cpsf:Physical","rdf:type","cpsf:Concern").
input("cpsf:Physical","rdf:type","owl:NamedIndividual").
input("cpsf:nextFC","rdfs:comment","next level of functional decomposition").
input("cpsf:nextFC","rdfs:range","cpsf:Function").
input("cpsf:nextFC","rdfs:domain","cpsf:Function").
input("cpsf:nextFC","rdf:type","owl:ObjectProperty").
input("cpsf:Adaptability","rdf:type","cpsf:Concern").
input("cpsf:Adaptability","rdf:type","owl:NamedIndividual").
input("cpsf:UseCase","cpsf:nextFC","cpsf:Scenario").
input("cpsf:UseCase","rdf:type","cpsf:UseCase").
input("cpsf:UseCase","rdf:type","owl:NamedIndividual").
input("cpsf:UseCase","rdfs:subClassOf","cpsf:Function").
input("cpsf:UseCase","rdf:type","owl:Class").
input("cpsf:Identity","cpsf:includesConcern","cpsf:Verification").
input("cpsf:Identity","cpsf:includesConcern","cpsf:ResourceIdentification").
input("cpsf:Identity","cpsf:includesConcern","cpsf:Provenance").
input("cpsf:Identity","cpsf:includesConcern","cpsf:DataIntegrity").
input("cpsf:Identity","cpsf:includesConcern","cpsf:Configuration").
input("cpsf:Identity","cpsf:includesConcern","cpsf:Authorization").
input("cpsf:Identity","cpsf:includesConcern","cpsf:Authentication").
input("cpsf:Identity","rdf:type","cpsf:Concern").
input("cpsf:Identity","rdf:type","owl:NamedIndividual").
input("cpsf:Data","cpsf:includesConcern","cpsf:Velocity").
input("cpsf:Data","cpsf:includesConcern","cpsf:RelationshipBetweenData").
input("cpsf:Data","cpsf:includesConcern","cpsf:OperationsOnData").
input("cpsf:Data","cpsf:includesConcern","cpsf:Identity").
input("cpsf:Data","cpsf:includesConcern","cpsf:DataSemantics").
input("cpsf:Data","rdf:type","cpsf:Aspect").
input("cpsf:Data","rdf:type","owl:NamedIndividual").
input("cpsf:DataIntegrity","rdf:type","cpsf:Concern").
input("cpsf:DataIntegrity","rdf:type","owl:NamedIndividual").
input("cpsf:Condition","rdfs:subClassOf","cpsf:ImpactRuleConcepts").
input("cpsf:Condition","rdf:type","owl:Class").
input("cpsf:Constructivity","rdf:type","cpsf:Concern").
input("cpsf:Constructivity","rdf:type","owl:NamedIndividual").
input("cpsf:Storage","rdf:type","cpsf:Concern").
input("cpsf:Storage","rdf:type","owl:NamedIndividual").
% Aspect
aspect(trustworthiness).

% Concern
concern(trustworthiness).
concern(safety).
concern(reliability).
concern(security).
concern(resilience).
concern(privacy).

concern(functional_safety).
concern(cyber_security).
concern(physical_security).
concern(predictability).
concern(manageability).
concern(dissociability).

concern(severity).
concern(frequency).
concern(controllability).
concern(confidentiality).
concern(integrity).
concern(availability).
concern(controls).
concern(transparency).
concern(availability).
concern(innovation).

concern(encryption).
concern(privacy_policy).
concern(protection).
concern(software_patches).
concern(hardware_patches).
concern(license).
concern(authorization).
concern(authentication).
concern(roles).
concern(privileges).
concern(permissions).

% subconcern.
subconcern(trustworthiness,safety).
subconcern(trustworthiness,reliability).
subconcern(trustworthiness,security).
subconcern(trustworthiness,resilience).
subconcern(trustworthiness,privacy).

subconcern(safety,functional_safety).

subconcern(security,cyber_security).
subconcern(security,physical_security).

subconcern(privacy,predictability).
subconcern(privacy,manageability).
subconcern(privacy,dissociability).

subconcern(functional_safety,severity).
subconcern(functional_safety,frequency).
subconcern(functional_safety,controllability).

subconcern(cyber_security,confidentiality).
subconcern(cyber_security,integrity).
subconcern(cyber_security,availability).

subconcern(physical_security,ultility).

subconcern(predictability,controls).
subconcern(predictability,transparency).
subconcern(predictability,innovation).

subconcern(confidentiality,encryption).
subconcern(confidentiality,privacy_policy).
subconcern(confidentiality,protection).

subconcern(availability,software_patches).
subconcern(availability,hardware_patches).
subconcern(availability,license).

subconcern(controls,authentication).
subconcern(controls,identity).

subconcern(identity,authorization).

% Property --- Requirements
property(data_encrypted).
property(conn_encrypted).
property(protocol_encrypted).

property(firewall_setup).
property(hidden_backdoor).
property(data_filtering).

property(software_licensed).
property(privacy_standard).

property(algo_AES).
property(algo_RSA).
property(algo_DES).

property(oAuth).
property(two_factors_auth).
property(finger_printing_auth).
property(single_auth).

property(secure_boot).

property(record_video_25fps).
property(record_video_50fps).

property(basic_mode).
property(advanced_mode).

property(devices_access_permission).
property(data_access_permission).

% Addressed : Relation Properties-Concerns
addressedBy(encryption,data_encrypted).
addressedBy(encryption,conn_encrypted).
addressedBy(encryption,protocol_encrypted).
addressedBy(encryption,algo_AES).
addressedBy(encryption,algo_RSA).

addressedBy(protection,firewall_setup).
addressedBy(protection,hidden_backdoor).
addressedBy(protection,data_filtering).

addressedBy(privacy_policy,software_licensed).
addressedBy(privacy_policy,privacy_standard).

addressedBy(authentication,oAuth).
addressedBy(authentication,single_auth).
addressedBy(authentication,two_factors_auth).
addressedBy(authentication,finger_printing_auth).

addressedBy(integrity,secure_boot).

addressedBy(integrity,basic_mode).
addressedBy(integrity,advanced_mode).

addressedBy(frequency,record_video_25fps).
addressedBy(frequency,record_video_50fps).

addressedBy(authorization,devices_access_permission).
addressedBy(authorization,data_access_permission).

% Component and Relation
component(sam).
component(cam).

relation(cam,data_encrypted,"CAM access to encrypted data").
relation(cam,secure_boot,"CAM use Secure Bot").
relation(cam,data_filtering,"CAM has been checked").
%relation(cam,record_video_50fps,"CAM has been recorded 50FPS").
relation(cam,advanced_mode,"CAM used Advanced mode").
relation(cam,devices_access_permission,"Have to have permission to access CAM").

relation(sam,data_encrypted,"SAM access to encrypted data").
relation(sam,secure_boot,"SAM use Secure Bot").
relation(sam,software_licensed,"SAM used licensed software").
relation(sam,two_factors_auth,"Access to SAM required 2-factors authentication").
relation(sam,firewall_setup,"Firewall protected SAM").
relation(sam,data_access_permission,"Have to have permission to access CAM").

% ====================================================
% ======Observation for Initial State
obs(data_encrypted,true).
obs(data_filtering,true).
obs(software_licensed,true).
obs(two_factors_auth,false). % Change here to test
obs(secure_boot,true).
obs(record_video_50fps,true).
obs(advanced_mode,true).
obs(firewall_setup,false). % Change here to test
obs(devices_access_permission,true).
obs(data_access_permission,true).
obs(availablePatch(two_factors_auth),true).




%=================================
#const n = 2.
step(0..n).
%=====Satisfaction Reasoning======

%h(P,0) :- obs(P,true), property(P).
-h(P,0) :- obs(P,false).
%h(P,0) :- obs(availablePatch(P),true), property(P).
h(P,0) :- obs(P,true).

-h(sat(C),T) :- -h(P,T), property(P), step(T), 
                addressedBy(C,P).
-h(sat(X),T) :- concern(X), concern(Y), 
                subconcern(X,Y), not h(sat(Y),T), step(T).
-h(sat(X),T) :- concern(X), concern(Y), 
                subconcern(X,Y), -h(sat(Y),T), step(T).
h(sat(C),T) :- not -h(sat(C),T), concern(C), step(T).

% ---------------------------------------------
% ==========  ACTIONS and CHANGES =============
% ---------------------------------------------
% Generate action
1{occurs(A,T):action(A)}1 :- step(T), T<n.
:- occurs(A,T), not executable(A,T).

% Inertial axioms
fluent(F) :- property(F).
fluent(availablePatch(F)) :- property(F).
%fluent(sat(A)) :- concern(A).

h(F,T+1)    :- h(F,T), not -h(F,T+1), step(T), fluent(F).
-h(F,T+1)   :- -h(F,T), not h(F,T+1), step(T), fluent(F).

% Goal check type 2
%goal(G) :- h(sat(trustworthiness),G), step(G).
%success :- goal(G), G <= n, step(G).
%:- not success.

% Goal check type 1
:- not h(sat(C),n), concern(C).
%:- not h(sat(A),n), aspect(A).

% Actions
action(tOn(X)) :- property(X).
action(patch(X)) :- property(X).

%% Preconditions
%executable(tOn(detect_No_passenger),T) :- -h(detect_No_passenger,T), step(T).
%executable(tOn(control_speed),T) :- -h(control_speed,T), step(T).
%executable(patch(control_speed),T) :- -h(control_speed,T), step(T).

executable(tOn(X),T) :- -h(X,T), property(X), step(T).
executable(patch(X),T) :- -h(X,T), h(availablePatch(X),T), property(X), step(T).

%% Effects
h(X,T+1) :- occurs(tOn(X),T), step(T).
h(X,T+1) :- occurs(patch(X),T), step(T).

%:- occurs(A1,T), occurs(A2,T), A1 != A2.

% ---------------------------------------------
% ==========  Probabilistic of success ========
% ---------------------------------------------
prob_success(tOn(detect_No_passenger),80).
prob_success(tOn(control_speed),70).
prob_success(patch(control_speed),30).

prob_success(tOn(firewall_setup),60).
prob_success(tOn(two_factors_auth),30).
prob_success(patch(two_factors_auth),20).

% ---------------------------------------------

h(prob_of_state(100),0).
h(prob_of_state(P2),T2) :- step(T),step(T2), T2=T+1, 
                           h(prob_of_state(P),T), 
                           occurs(A,T), 
                           prob_success(A,PSucc),
                           P2a=P*PSucc,P2=P2a/100.
known_prob_success(T)   :- step(T), occurs(A,T), 
                           prob_success(A,PSucc).
unknown_prob_success(T) :- step(T), not known_prob_success(T).
h(prob_of_state(P),T2)  :- step(T), step(T2), T2=T+1, 
                           h(prob_of_state(P),T), 
                           unknown_prob_success(T).
last_step(T):- step(T),T2=T+1, not step(T2).
check_p(P,T) :- h(prob_of_state(P),T).
%last_step(1). 
#maximize{P : h(prob_of_state(P),T), last_step(T)}.

% ---------------------------------------------
% ------ Output Interface ------

output_headings("Action","Prob. Success of Action","Prob. of State","Step").

% Support : Identify the last step in the input
last_step(S) :- step(S), S2=S+1, not step(S2).

output(A,P,Pr,S) :- occurs(A,S), 
                    prob_success(A,P), 
                    action(A), 
                    h(prob_of_state(Pr),S), 
                    step(S).

output("-","-",Pr,S) :- h(prob_of_state(Pr),S), last_step(S).


% ====== SHOW ========
%#show output_headings/6.
%#show output/6.
