input("cpsf:DataSemantics","cpsf:includesConcern","cpsf:Meaning").
input("cpsf:DataSemantics","cpsf:includesConcern","cpsf:Granularity").
input("cpsf:DataSemantics","cpsf:includesConcern","cpsf:DataModels").
input("cpsf:DataSemantics","rdf:type","cpsf:Concern").
input("cpsf:DataSemantics","rdf:type","owl:NamedIndividual").
input("cpsf:Manageability","rdf:type","cpsf:Concern").
input("cpsf:Manageability","rdf:type","owl:NamedIndividual").
input("cpsf:Procureability","rdf:type","cpsf:Concern").
input("cpsf:Procureability","rdf:type","owl:NamedIndividual").
input("cpsf:Engineerability","rdf:type","cpsf:Concern").
input("cpsf:Engineerability","rdf:type","owl:NamedIndividual").
input("cpsf:Verification","rdf:type","cpsf:Concern").
input("cpsf:Verification","rdf:type","owl:NamedIndividual").
input("cpsf:HumanFactors","rdf:type","cpsf:Concern").
input("cpsf:HumanFactors","rdf:type","owl:NamedIndividual").
input("cpsf:Cost","rdf:type","cpsf:Concern").
input("cpsf:Cost","rdf:type","owl:NamedIndividual").
input("cpsf:ir0002","rdfs:comment","cpsf:Integrity is addressed by property cpsf:Input1SecBoot").
input("cpsf:ir0002","cpsf:hasCondition","cpsf:c0002_01").
input("cpsf:ir0002","cpsf:addressesPolarity","cpsf:positive").
input("cpsf:ir0002","cpsf:addressesConcern","cpsf:Integrity").
input("cpsf:ir0002","cpsf:addressesAtFunc","cpsf:bc1").
input("cpsf:ir0002","rdf:type","cpsf:ImpactRule").
input("cpsf:ir0002","rdf:type","owl:NamedIndividual").
input("cpsf:conditionProperty","rdfs:comment","pg 15").
input("cpsf:conditionProperty","rdfs:comment","CPS-specific").
input("cpsf:conditionProperty","rdfs:range","cpsf:Property").
input("cpsf:conditionProperty","rdfs:domain","cpsf:Condition").
input("cpsf:conditionProperty","rdf:type","owl:ObjectProperty").
input("cpsf:RealizationFacet","rdfs:comment","CPS-independent").
input("cpsf:RealizationFacet","rdf:type","cpsf:Facet").
input("cpsf:RealizationFacet","rdf:type","owl:NamedIndividual").
input("cpsf:Communication","rdf:type","cpsf:Concern").
input("cpsf:Communication","rdf:type","owl:NamedIndividual").
input("cpsf:OperationsOnData","cpsf:includesConcern","cpsf:Transformation").
input("cpsf:OperationsOnData","cpsf:includesConcern","cpsf:Storage").
input("cpsf:OperationsOnData","cpsf:includesConcern","cpsf:Fusion").
input("cpsf:OperationsOnData","cpsf:includesConcern","cpsf:Analytics").
input("cpsf:OperationsOnData","cpsf:includesConcern","cpsf:Aggregation_Disaggregation").
input("cpsf:OperationsOnData","rdf:type","cpsf:Concern").
input("cpsf:OperationsOnData","rdf:type","owl:NamedIndividual").
input("cpsf:TimeAwareness","rdf:type","cpsf:Concern").
input("cpsf:TimeAwareness","rdf:type","owl:NamedIndividual").
input("cpsf:Business","rdf:type","owl:NamedIndividual").
input("cpsf:Business","cpsf:includesConcern","cpsf:Planning").
input("cpsf:Business","cpsf:includesConcern","cpsf:Enterprise").
input("cpsf:Business","cpsf:includesConcern","cpsf:TimeToMarket").
input("cpsf:Business","cpsf:includesConcern","cpsf:Regulatory").
input("cpsf:Business","rdf:type","cpsf:Aspect").
input("cpsf:Business","cpsf:includesConcern","cpsf:Quality").
input("cpsf:Business","cpsf:includesConcern","cpsf:Cost").
input("cpsf:Business","cpsf:includesConcern","cpsf:Environment").
input("cpsf:Business","cpsf:includesConcern","cpsf:Policy").
input("cpsf:Business","cpsf:includesConcern","cpsf:Utility").
input("cpsf:Environment","rdf:type","cpsf:Concern").
input("cpsf:Environment","rdf:type","owl:NamedIndividual").
input("cpsf:refinedInto","rdfs:range","cpsf:Function").
input("cpsf:refinedInto","rdfs:domain","cpsf:Function").
input("cpsf:refinedInto","rdf:type","owl:ObjectProperty").
input("cpsf:Integrity","cpsf:relevantToFunc","cpsf:bc1").
input("cpsf:Integrity","rdf:type","cpsf:Concern").
input("cpsf:Integrity","rdf:type","owl:NamedIndividual").
input("cpsf:Measurability","rdf:type","cpsf:Concern").
input("cpsf:Measurability","rdf:type","owl:NamedIndividual").
input("cpsf:Discoverability","rdf:type","cpsf:Concern").
input("cpsf:Discoverability","rdf:type","owl:NamedIndividual").
input("cpsf:Function","rdfs:subClassOf","cpsf:CPSFrameworkConcept").
input("cpsf:Function","rdf:type","owl:Class").
input("cpsf:addressesPolarity","rdfs:range","cpsf:ImpactPolarity").
input("cpsf:addressesPolarity","rdfs:domain","cpsf:ImpactRule").
input("cpsf:addressesPolarity","rdf:type","owl:ObjectProperty").
input("cpsf:SAMEncryptedMem","rdfs:comment","SAM uses encrypted memory").
input("cpsf:SAMEncryptedMem","cpsf:atomicStatement","encrypted_mem_sam").
input("cpsf:SAMEncryptedMem","cpsf:hasType","cpsf:PropertyType_Assertion").
input("cpsf:SAMEncryptedMem","rdf:type","cpsf:Property").
input("cpsf:SAMEncryptedMem","rdf:type","owl:NamedIndividual").
input("cpsf:Input1SecBoot","rdfs:comment","Input Device 1 uses secure boot").
input("cpsf:Input1SecBoot","cpsf:atomicStatement","sec_boot_input1").
input("cpsf:Input1SecBoot","cpsf:hasType","cpsf:PropertyType_Assertion").
input("cpsf:Input1SecBoot","rdf:type","cpsf:Property").
input("cpsf:Input1SecBoot","rdf:type","owl:NamedIndividual").
input("cpsf:positive","rdf:type","cpsf:ImpactPolarity").
input("cpsf:positive","rdf:type","owl:NamedIndividual").
input("cpsf:DeviceIdentification","rdf:type","cpsf:Concern").
input("cpsf:DeviceIdentification","rdf:type","owl:NamedIndividual").
input("cpsf:Analytics","rdf:type","cpsf:Concern").
input("cpsf:Analytics","rdf:type","owl:NamedIndividual").
input("cpsf:c0005_01","cpsf:conditionProperty","cpsf:SAMEncryptedMem").
input("cpsf:c0005_01","cpsf:conditionPolarity","cpsf:positive").
input("cpsf:c0005_01","rdf:type","cpsf:Condition").
input("cpsf:c0005_01","rdf:type","owl:NamedIndividual").
input("cpsf:RelatedData","rdf:type","cpsf:Concern").
input("cpsf:RelatedData","rdf:type","owl:NamedIndividual").
input("cpsf:ir0005","rdfs:comment","cpsf:Confidentiality is addressed by property cpsf:SAMEncryptedMem").
input("cpsf:ir0005","cpsf:hasCondition","cpsf:c0005_01").
input("cpsf:ir0005","cpsf:addressesPolarity","cpsf:positive").
input("cpsf:ir0005","cpsf:addressesConcern","cpsf:Confidentiality").
input("cpsf:ir0005","cpsf:addressesAtFunc","cpsf:bc1").
input("cpsf:ir0005","rdf:type","cpsf:ImpactRule").
input("cpsf:ir0005","rdf:type","owl:NamedIndividual").
input("cpsf:Meaning","rdf:type","cpsf:Concern").
input("cpsf:Meaning","rdf:type","owl:NamedIndividual").
input("cpsf:atomicStatement","rdf:type","owl:DatatypeProperty").
input("cpsf:Authentication","rdf:type","cpsf:Concern").
input("cpsf:Authentication","rdf:type","owl:NamedIndividual").
input("cpsf:DataQuality","rdf:type","cpsf:Concern").
input("cpsf:DataQuality","rdf:type","owl:NamedIndividual").
input("cpsf:Property","rdfs:comment","pg 15").
input("cpsf:Property","rdfs:subClassOf","cpsf:CPSFrameworkConcept").
input("cpsf:Property","rdf:type","owl:Class").
input("cpsf:c0002_01","cpsf:conditionProperty","cpsf:Input1SecBoot").
input("cpsf:c0002_01","cpsf:conditionPolarity","cpsf:positive").
input("cpsf:c0002_01","rdf:type","cpsf:Condition").
input("cpsf:c0002_01","rdf:type","owl:NamedIndividual").
input("cpsf:Reliability","rdf:type","cpsf:Concern").
input("cpsf:Reliability","rdf:type","owl:NamedIndividual").
input("cpsf:Artifact","rdfs:subClassOf","cpsf:CPSFrameworkConcept").
input("cpsf:Artifact","rdf:type","owl:Class").
input("cpsf:hasBC","rdfs:range","cpsf:BusinessCase").
input("cpsf:hasBC","rdfs:domain","cpsf:Application").
input("cpsf:hasBC","rdfs:subPropertyOf","owl:topObjectProperty").
input("cpsf:hasBC","rdf:type","owl:ObjectProperty").
input("cpsf:BusinessCase","cpsf:nextFC","cpsf:UseCase").
input("cpsf:BusinessCase","rdf:type","cpsf:BusinessCase").
input("cpsf:BusinessCase","rdf:type","owl:NamedIndividual").
input("cpsf:BusinessCase","rdfs:subClassOf","cpsf:Function").
input("cpsf:BusinessCase","rdf:type","owl:Class").
input("cpsf:Synchronization","rdf:type","cpsf:Concern").
input("cpsf:Synchronization","rdf:type","owl:NamedIndividual").
input("cpsf:TimeIntervalAndLatencyControl","rdf:type","cpsf:Concern").
input("cpsf:TimeIntervalAndLatencyControl","rdf:type","owl:NamedIndividual").
input("cpsf:Safety","rdf:type","cpsf:Concern").
input("cpsf:Safety","rdf:type","owl:NamedIndividual").
input("cpsf:Privacy","rdf:type","cpsf:Concern").
input("cpsf:Privacy","rdf:type","owl:NamedIndividual").
input("cpsf:ConfigurationForLeastFFunctionality","rdf:type","cpsf:Concern").
input("cpsf:ConfigurationForLeastFFunctionality","rdf:type","owl:NamedIndividual").
input("cpsf:Complexity","rdf:type","cpsf:Concern").
input("cpsf:Complexity","rdf:type","owl:NamedIndividual").
input("cpsf:Actuation","rdf:type","cpsf:Concern").
input("cpsf:Actuation","rdf:type","owl:NamedIndividual").
input("cpsf:Confidentiality","cpsf:relevantToFunc","cpsf:bc1").
input("cpsf:Confidentiality","rdf:type","cpsf:Concern").
input("cpsf:Confidentiality","rdf:type","owl:NamedIndividual").
input("cpsf:uc1","rdf:type","cpsf:UseCase").
input("cpsf:uc1","rdf:type","owl:NamedIndividual").
input("cpsf:ManagingTimingAndLatency","rdf:type","cpsf:Concern").
input("cpsf:ManagingTimingAndLatency","rdf:type","owl:NamedIndividual").
input("cpsf:Usability","rdf:type","cpsf:Concern").
input("cpsf:Usability","rdf:type","owl:NamedIndividual").
input("cpsf:TimeOfData","rdf:type","cpsf:Concern").
input("cpsf:TimeOfData","rdf:type","owl:NamedIndividual").
input("cpsf:Producibility","rdf:type","cpsf:Concern").
input("cpsf:Producibility","rdf:type","owl:NamedIndividual").
input("cpsf:Planning","rdf:type","cpsf:Concern").
input("cpsf:Planning","rdf:type","owl:NamedIndividual").
input("cpsf:hasCondition","rdfs:comment","pg 15").
input("cpsf:hasCondition","rdfs:comment","CPS-specific").
input("cpsf:hasCondition","rdfs:range","cpsf:Condition").
input("cpsf:hasCondition","rdfs:domain","cpsf:ImpactRule").
input("cpsf:hasCondition","rdf:type","owl:ObjectProperty").
input("cpsf:Configuration","rdf:type","cpsf:Concern").
input("cpsf:Configuration","rdf:type","owl:NamedIndividual").
input("cpsf:DesignElement","rdfs:subClassOf","cpsf:Property").
input("cpsf:DesignElement","rdf:type","owl:Class").
input("cpsf:StatesAndModes","rdf:type","cpsf:Concern").
input("cpsf:StatesAndModes","rdf:type","owl:NamedIndividual").
input("cpsf:Aggregation_Disaggregation","rdf:type","cpsf:Concern").
input("cpsf:Aggregation_Disaggregation","rdf:type","owl:NamedIndividual").
input("cpsf:Test","rdfs:subClassOf","cpsf:Property").
input("cpsf:Test","rdf:type","owl:Class").
input("cpsf:Scenario","rdf:type","cpsf:Scenario").
input("cpsf:Scenario","rdf:type","owl:NamedIndividual").
input("cpsf:Scenario","rdfs:subClassOf","cpsf:Function").
input("cpsf:Scenario","rdf:type","owl:Class").
input("cpsf:Activity","rdfs:subClassOf","cpsf:CPSFrameworkConcept").
input("cpsf:Activity","rdf:type","owl:Class").
input("cpsf:ConceptualizationFacet","rdfs:comment","CPS-independent").
input("cpsf:ConceptualizationFacet","rdf:type","cpsf:Facet").
input("cpsf:ConceptualizationFacet","rdf:type","owl:NamedIndividual").
input("cpsf:ImpactRule","rdfs:subClassOf","cpsf:ImpactRuleConcepts").
input("cpsf:ImpactRule","rdf:type","owl:Class").
input("cpsf:ir0003","rdfs:comment","cpsf:Functionality is addressed by property cpsf:Input1ConsistentReadingFreq").
input("cpsf:ir0003","cpsf:hasCondition","cpsf:c0003_01").
input("cpsf:ir0003","cpsf:addressesPolarity","cpsf:positive").
input("cpsf:ir0003","cpsf:addressesConcern","cpsf:Functionality").
input("cpsf:ir0003","cpsf:addressesAtFunc","cpsf:bc1").
input("cpsf:ir0003","rdf:type","cpsf:ImpactRule").
input("cpsf:ir0003","rdf:type","owl:NamedIndividual").
input("cpsf:relevantToFunc","rdfs:range","cpsf:Function").
input("cpsf:relevantToFunc","rdfs:domain","cpsf:Concern").
input("cpsf:relevantToFunc","rdf:type","owl:ObjectProperty").
input("<http://www.asklab.tk/ontologies/CPS-Framework>","rdf:type","owl:Ontology").
input("cpsf:Sensing","rdf:type","cpsf:Concern").
input("cpsf:Sensing","rdf:type","owl:NamedIndividual").
input("cpsf:Deployability","rdf:type","cpsf:Concern").
input("cpsf:Deployability","rdf:type","owl:NamedIndividual").
input("cpsf:PhysicalSecurity","rdf:type","cpsf:Concern").
input("cpsf:PhysicalSecurity","rdf:type","owl:NamedIndividual").
input("cpsf:Monitorability","rdf:type","cpsf:Concern").
input("cpsf:Monitorability","rdf:type","owl:NamedIndividual").
input("cpsf:Provenance","rdf:type","cpsf:Concern").
input("cpsf:Provenance","rdf:type","owl:NamedIndividual").
input("cpsf:Resilience","rdf:type","cpsf:Concern").
input("cpsf:Resilience","rdf:type","owl:NamedIndividual").
input("cpsf:Functionality","cpsf:relevantToFunc","cpsf:bc1").
input("cpsf:Functionality","rdf:type","cpsf:Concern").
input("cpsf:Functionality","rdf:type","owl:NamedIndividual").
input("cpsf:Timing","cpsf:includesConcern","cpsf:TimeIntervalAndLatencyControl").
input("cpsf:Timing","cpsf:includesConcern","cpsf:TimeAwareness").
input("cpsf:Timing","cpsf:includesConcern","cpsf:Synchronization").
input("cpsf:Timing","cpsf:includesConcern","cpsf:ManagingTimingAndLatency").
input("cpsf:Timing","cpsf:includesConcern","cpsf:LogicalTime").
input("cpsf:Timing","rdf:type","cpsf:Aspect").
input("cpsf:Timing","rdf:type","owl:NamedIndividual").
input("cpsf:c0004_01","cpsf:conditionProperty","cpsf:Input1Modes").
input("cpsf:c0004_01","cpsf:conditionPolarity","cpsf:positive").
input("cpsf:c0004_01","rdf:type","cpsf:Condition").
input("cpsf:c0004_01","rdf:type","owl:NamedIndividual").
input("cpsf:Requirement","rdfs:subClassOf","cpsf:Property").
input("cpsf:Requirement","rdf:type","owl:Class").
input("cpsf:Security","cpsf:includesConcern","cpsf:PhysicalSecurity").
input("cpsf:Security","cpsf:includesConcern","cpsf:Cybersecurity").
input("cpsf:Security","rdf:type","cpsf:Concern").
input("cpsf:Security","rdf:type","owl:NamedIndividual").
input("cpsf:includesArtifact","rdfs:comment","pg 16").
input("cpsf:includesArtifact","rdfs:comment","CPS-specific").
input("cpsf:includesArtifact","rdfs:range","cpsf:Artifact").
input("cpsf:includesArtifact","rdfs:domain","cpsf:Facet").
input("cpsf:includesArtifact","rdf:type","owl:ObjectProperty").
input("cpsf:Uncertainty","rdf:type","cpsf:Concern").
input("cpsf:Uncertainty","rdf:type","owl:NamedIndividual").
input("cpsf:PropertyType","rdfs:subClassOf","cpsf:CPSFrameworkConcept").
input("cpsf:PropertyType","rdf:type","owl:Class").
input("cpsf:LocationOfData","rdf:type","cpsf:Concern").
input("cpsf:LocationOfData","rdf:type","owl:NamedIndividual").
input("cpsf:Application","rdfs:subClassOf","cpsf:CPSFrameworkConcept").
input("cpsf:Application","rdf:type","owl:Class").
input("cpsf:ir0006","rdfs:comment","cpsf:Confidentiality is addressed by property cpsf:Input1EncryptedMem").
input("cpsf:ir0006","cpsf:hasCondition","cpsf:c0006_01").
input("cpsf:ir0006","cpsf:addressesPolarity","cpsf:positive").
input("cpsf:ir0006","cpsf:addressesConcern","cpsf:Confidentiality").
input("cpsf:ir0006","cpsf:addressesAtFunc","cpsf:bc1").
input("cpsf:ir0006","rdf:type","cpsf:ImpactRule").
input("cpsf:ir0006","rdf:type","owl:NamedIndividual").
input("cpsf:c0001_01","cpsf:conditionProperty","cpsf:SAMSecBoot").
input("cpsf:c0001_01","cpsf:conditionPolarity","cpsf:positive").
input("cpsf:c0001_01","rdf:type","cpsf:Condition").
input("cpsf:c0001_01","rdf:type","owl:NamedIndividual").
input("cpsf:Disposability","rdf:type","cpsf:Concern").
input("cpsf:Disposability","rdf:type","owl:NamedIndividual").
input("cpsf:ImpactRuleConcepts","rdfs:subClassOf","cpsf:CPSFrameworkConcept").
input("cpsf:ImpactRuleConcepts","rdf:type","owl:Class").
input("cpsf:ResourceIdentification","cpsf:includesConcern","cpsf:UserIdentification").
input("cpsf:ResourceIdentification","cpsf:includesConcern","cpsf:ObjectIdentification").
input("cpsf:ResourceIdentification","cpsf:includesConcern","cpsf:DeviceIdentification").
input("cpsf:ResourceIdentification","cpsf:includesConcern","cpsf:ClassIdentification").
input("cpsf:ResourceIdentification","rdf:type","cpsf:Concern").
input("cpsf:ResourceIdentification","rdf:type","owl:NamedIndividual").
input("cpsf:Polymorphism","rdf:type","cpsf:Concern").
input("cpsf:Polymorphism","rdf:type","owl:NamedIndividual").
input("cpsf:app1","cpsf:hasBC","cpsf:bc1").
input("cpsf:app1","rdf:type","cpsf:Application").
input("cpsf:app1","rdf:type","owl:NamedIndividual").
input("cpsf:TimeToMarket","rdf:type","cpsf:Concern").
input("cpsf:TimeToMarket","rdf:type","owl:NamedIndividual").
input("cpsf:Input1EncryptedMem","rdfs:comment","Input Device 1 uses encrypted memory").
input("cpsf:Input1EncryptedMem","cpsf:atomicStatement","encrypted_mem_input1").
input("cpsf:Input1EncryptedMem","cpsf:hasType","cpsf:PropertyType_Assertion").
input("cpsf:Input1EncryptedMem","rdf:type","cpsf:Property").
input("cpsf:Input1EncryptedMem","rdf:type","owl:NamedIndividual").
input("cpsf:Controllability","rdf:type","cpsf:Concern").
input("cpsf:Controllability","rdf:type","owl:NamedIndividual").
input("cpsf:PropertyType_Capability","rdf:type","cpsf:PropertyType").
input("cpsf:PropertyType_Capability","rdf:type","owl:NamedIndividual").
input("cpsf:addressesAtFunc","rdfs:range","cpsf:Function").
input("cpsf:addressesAtFunc","rdfs:domain","cpsf:ImpactRule").
input("cpsf:addressesAtFunc","rdf:type","owl:ObjectProperty").
input("cpsf:includesConcern","rdfs:comment","pg 15").
input("cpsf:includesConcern","rdfs:comment","CPS-independent").
input("cpsf:includesConcern","rdfs:range","cpsf:Concern").
input("cpsf:includesConcern","rdfs:domain","cpsf:Concern").
input("cpsf:includesConcern","rdf:type","owl:ObjectProperty").
input("cpsf:Composition","cpsf:includesConcern","cpsf:Discoverability").
input("cpsf:Composition","cpsf:includesConcern","cpsf:Constructivity").
input("cpsf:Composition","cpsf:includesConcern","cpsf:Complexity").
input("cpsf:Composition","cpsf:includesConcern","cpsf:Adaptability").
input("cpsf:Composition","rdf:type","cpsf:Aspect").
input("cpsf:Composition","rdf:type","owl:NamedIndividual").
input("cpsf:addressesConcern","rdfs:comment","pg 15").
input("cpsf:addressesConcern","rdfs:comment","CPS-specific").
input("cpsf:addressesConcern","rdfs:range","cpsf:Concern").
input("cpsf:addressesConcern","rdfs:domain","cpsf:ImpactRule").
input("cpsf:addressesConcern","rdf:type","owl:ObjectProperty").
input("cpsf:Concern","rdfs:comment","pg 15").
input("cpsf:Concern","rdfs:comment","all instances are CPS-independent").
input("cpsf:Concern","rdfs:subClassOf","cpsf:CPSFrameworkConcept").
input("cpsf:Concern","rdf:type","owl:Class").
input("cpsf:Quality","rdf:type","cpsf:Concern").
input("cpsf:Quality","rdf:type","owl:NamedIndividual").
input("cpsf:conditionPolarity","rdfs:range","cpsf:ImpactPolarity").
input("cpsf:conditionPolarity","rdfs:domain","cpsf:Condition").
input("cpsf:conditionPolarity","rdf:type","owl:ObjectProperty").
input("cpsf:ComponentInventory","cpsf:relevantToFunc","cpsf:bc1").
input("cpsf:ComponentInventory","rdf:type","cpsf:Concern").
input("cpsf:ComponentInventory","rdf:type","owl:NamedIndividual").
input("cpsf:Inheritance","rdf:type","cpsf:Concern").
input("cpsf:Inheritance","rdf:type","owl:NamedIndividual").
input("cpsf:Enterprise","rdf:type","cpsf:Concern").
input("cpsf:Enterprise","rdf:type","owl:NamedIndividual").
input("cpsf:Behavioral","rdf:type","cpsf:Concern").
input("cpsf:Behavioral","rdf:type","owl:NamedIndividual").
input("cpsf:Lifecycle","cpsf:includesConcern","cpsf:Producibility").
input("cpsf:Lifecycle","cpsf:includesConcern","cpsf:Procureability").
input("cpsf:Lifecycle","cpsf:includesConcern","cpsf:Operatability").
input("cpsf:Lifecycle","cpsf:includesConcern","cpsf:Maintainability").
input("cpsf:Lifecycle","cpsf:includesConcern","cpsf:Engineerability").
input("cpsf:Lifecycle","cpsf:includesConcern","cpsf:Disposability").
input("cpsf:Lifecycle","cpsf:includesConcern","cpsf:Deployability").
input("cpsf:Lifecycle","rdf:type","cpsf:Aspect").
input("cpsf:Lifecycle","rdf:type","owl:NamedIndividual").
input("cpsf:ir0001","rdfs:comment","cpsf:Integrity is addressed by property cpsf:SAMSecBoot").
input("cpsf:ir0001","cpsf:hasCondition","cpsf:c0001_01").
input("cpsf:ir0001","cpsf:addressesPolarity","cpsf:positive").
input("cpsf:ir0001","cpsf:addressesConcern","cpsf:Integrity").
input("cpsf:ir0001","cpsf:addressesAtFunc","cpsf:bc1").
input("cpsf:ir0001","rdf:type","cpsf:ImpactRule").
input("cpsf:ir0001","rdf:type","owl:NamedIndividual").
input("cpsf:ConfigurationManagement","rdf:type","cpsf:Concern").
input("cpsf:ConfigurationManagement","rdf:type","owl:NamedIndividual").
input("cpsf:uc2","rdf:type","cpsf:UseCase").
input("cpsf:uc2","rdf:type","owl:NamedIndividual").
input("cpsf:ImpactPolarity","rdfs:subClassOf","cpsf:ImpactRuleConcepts").
input("cpsf:ImpactPolarity","rdf:type","owl:Class").
input("cpsf:includesActivity","rdfs:comment","pg 16").
input("cpsf:includesActivity","rdfs:comment","CPS-specific").
input("cpsf:includesActivity","rdfs:range","cpsf:Activity").
input("cpsf:includesActivity","rdfs:domain","cpsf:Facet").
input("cpsf:includesActivity","rdf:type","owl:ObjectProperty").
input("cpsf:Maintainability","cpsf:includesConcern","cpsf:ConfigurationManagement").
input("cpsf:Maintainability","cpsf:includesConcern","cpsf:ConfigurationForLeastFFunctionality").
input("cpsf:Maintainability","cpsf:includesConcern","cpsf:ComponentInventory").
input("cpsf:Maintainability","rdf:type","cpsf:Concern").
input("cpsf:Maintainability","rdf:type","owl:NamedIndividual").
input("cpsf:DataModels","rdf:type","cpsf:Concern").
input("cpsf:DataModels","rdf:type","owl:NamedIndividual").
input("cpsf:hasType","rdfs:range","cpsf:PropertyType").
input("cpsf:hasType","rdfs:domain","cpsf:Property").
input("cpsf:hasType","rdf:type","owl:ObjectProperty").
input("cpsf:Trustworthiness","cpsf:includesConcern","cpsf:Security").
input("cpsf:Trustworthiness","cpsf:includesConcern","cpsf:Safety").
input("cpsf:Trustworthiness","cpsf:includesConcern","cpsf:Resilience").
input("cpsf:Trustworthiness","cpsf:includesConcern","cpsf:Reliability").
input("cpsf:Trustworthiness","cpsf:includesConcern","cpsf:Privacy").
input("cpsf:Trustworthiness","rdf:type","cpsf:Aspect").
input("cpsf:Trustworthiness","rdf:type","owl:NamedIndividual").
input("cpsf:Functional","cpsf:includesConcern","cpsf:Sensing").
input("cpsf:Functional","cpsf:includesConcern","cpsf:Measurability").
input("cpsf:Functional","cpsf:includesConcern","cpsf:Uncertainty").
input("cpsf:Functional","cpsf:includesConcern","cpsf:Manageability").
input("cpsf:Functional","cpsf:includesConcern","cpsf:StatesAndModes").
input("cpsf:Functional","cpsf:includesConcern","cpsf:Functionality").
input("cpsf:Functional","cpsf:includesConcern","cpsf:Communication").
input("cpsf:Functional","cpsf:includesConcern","cpsf:Performance").
input("cpsf:Functional","cpsf:includesConcern","cpsf:Controllability").
input("cpsf:Functional","cpsf:includesConcern","cpsf:Actuation").
input("cpsf:Functional","rdf:type","cpsf:Aspect").
input("cpsf:Functional","cpsf:includesConcern","cpsf:PhysicalContext").
input("cpsf:Functional","cpsf:includesConcern","cpsf:Monitorability").
input("cpsf:Functional","rdf:type","owl:NamedIndividual").
input("cpsf:Functional","cpsf:includesConcern","cpsf:Physical").
input("cpsf:Fusion","rdf:type","cpsf:Concern").
input("cpsf:Fusion","rdf:type","owl:NamedIndividual").
input("cpsf:PhysicalContext","rdf:type","cpsf:Concern").
input("cpsf:PhysicalContext","rdf:type","owl:NamedIndividual").
input("cpsf:Authorization","rdf:type","cpsf:Concern").
input("cpsf:Authorization","rdf:type","owl:NamedIndividual").
input("cpsf:Input1Modes","rdfs:comment","Input Device 1 should be capable of operating in low-speed mode and in high-speed mode").
input("cpsf:Input1Modes","cpsf:atomicStatement","slow_mode_input1").
input("cpsf:Input1Modes","cpsf:hasType","cpsf:PropertyType_Capability").
input("cpsf:Input1Modes","rdf:type","cpsf:Property").
input("cpsf:Input1Modes","rdf:type","owl:NamedIndividual").
input("cpsf:Availability","rdf:type","cpsf:Concern").
input("cpsf:Availability","rdf:type","owl:NamedIndividual").
input("cpsf:ClassIdentification","rdf:type","cpsf:Concern").
input("cpsf:ClassIdentification","rdf:type","owl:NamedIndividual").
input("cpsf:Judgment","rdfs:subClassOf","cpsf:Property").
input("cpsf:Judgment","rdf:type","owl:Class").
input("cpsf:RelationshipBetweenData","cpsf:includesConcern","cpsf:TimeOfData").
input("cpsf:RelationshipBetweenData","cpsf:includesConcern","cpsf:RelatedData").
input("cpsf:RelationshipBetweenData","cpsf:includesConcern","cpsf:Polymorphism").
input("cpsf:RelationshipBetweenData","cpsf:includesConcern","cpsf:LocationOfData").
input("cpsf:RelationshipBetweenData","cpsf:includesConcern","cpsf:Inheritance").
input("cpsf:RelationshipBetweenData","cpsf:includesConcern","cpsf:DirectionalityOfRelationships").
input("cpsf:RelationshipBetweenData","cpsf:includesConcern","cpsf:DataQuality").
input("cpsf:RelationshipBetweenData","rdf:type","cpsf:Concern").
input("cpsf:RelationshipBetweenData","rdf:type","owl:NamedIndividual").
input("cpsf:LogicalTime","rdf:type","cpsf:Concern").
input("cpsf:LogicalTime","rdf:type","owl:NamedIndividual").
input("cpsf:ObjectIdentification","rdf:type","cpsf:Concern").
input("cpsf:ObjectIdentification","rdf:type","owl:NamedIndividual").
input("cpsf:Cybersecurity","cpsf:includesConcern","cpsf:Integrity").
input("cpsf:Cybersecurity","cpsf:includesConcern","cpsf:Confidentiality").
input("cpsf:Cybersecurity","cpsf:includesConcern","cpsf:Availability").
input("cpsf:Cybersecurity","rdf:type","cpsf:Concern").
input("cpsf:Cybersecurity","rdf:type","owl:NamedIndividual").
input("cpsf:UserIdentification","rdf:type","cpsf:Concern").
input("cpsf:UserIdentification","rdf:type","owl:NamedIndividual").
input("cpsf:CPSFrameworkConcept","rdf:type","owl:Class").
input("cpsf:Input1ConsistentReadingFreq","rdfs:comment","Input Device 1 maintains consistent reading frequency").
input("cpsf:Input1ConsistentReadingFreq","cpsf:atomicStatement","consist_reading_freq_input1").
input("cpsf:Input1ConsistentReadingFreq","cpsf:hasType","cpsf:PropertyType_Assertion").
input("cpsf:Input1ConsistentReadingFreq","rdf:type","cpsf:Property").
input("cpsf:Input1ConsistentReadingFreq","rdf:type","owl:NamedIndividual").
input("cpsf:PropertyType_Assertion","rdf:type","cpsf:PropertyType").
input("cpsf:PropertyType_Assertion","rdf:type","owl:NamedIndividual").
input("cpsf:Policy","rdf:type","cpsf:Concern").
input("cpsf:Policy","rdf:type","owl:NamedIndividual").
input("cpsf:ir0004","rdfs:comment","cpsf:TimeIntervalAndLatencyControl is addressed by property cpsf:Input1Modes").
input("cpsf:ir0004","cpsf:hasCondition","cpsf:c0004_01").
input("cpsf:ir0004","cpsf:addressesPolarity","cpsf:positive").
input("cpsf:ir0004","cpsf:addressesConcern","cpsf:TimeIntervalAndLatencyControl").
input("cpsf:ir0004","cpsf:addressesAtFunc","cpsf:bc1").
input("cpsf:ir0004","rdf:type","cpsf:ImpactRule").
input("cpsf:ir0004","rdf:type","owl:NamedIndividual").
input("cpsf:Facet","rdfs:comment","pg 16").
input("cpsf:Facet","rdfs:comment","all instances are CPS-independent").
input("cpsf:Facet","rdfs:subClassOf","cpsf:CPSFrameworkConcept").
input("cpsf:Facet","rdf:type","owl:Class").
input("cpsf:Operatability","rdf:type","cpsf:Concern").
input("cpsf:Operatability","rdf:type","owl:NamedIndividual").
input("cpsf:negative","rdf:type","cpsf:ImpactPolarity").
input("cpsf:negative","rdf:type","owl:NamedIndividual").
input("cpsf:Velocity","rdf:type","cpsf:Concern").
input("cpsf:Velocity","rdf:type","owl:NamedIndividual").
input("cpsf:c0006_01","cpsf:conditionProperty","cpsf:Input1EncryptedMem").
input("cpsf:c0006_01","cpsf:conditionPolarity","cpsf:positive").
input("cpsf:c0006_01","rdf:type","cpsf:Condition").
input("cpsf:c0006_01","rdf:type","owl:NamedIndividual").
input("cpsf:Utility","rdf:type","cpsf:Concern").
input("cpsf:Utility","rdf:type","owl:NamedIndividual").
input("cpsf:DirectionalityOfRelationships","rdf:type","cpsf:Concern").
input("cpsf:DirectionalityOfRelationships","rdf:type","owl:NamedIndividual").
input("cpsf:Human","cpsf:includesConcern","cpsf:Usability").
input("cpsf:Human","cpsf:includesConcern","cpsf:HumanFactors").
input("cpsf:Human","rdf:type","cpsf:Aspect").
input("cpsf:Human","rdf:type","owl:NamedIndividual").
input("cpsf:Performance","rdf:type","cpsf:Concern").
input("cpsf:Performance","rdf:type","owl:NamedIndividual").
input("cpsf:Boundaries","cpsf:includesConcern","cpsf:Responsibility").
input("cpsf:Boundaries","cpsf:includesConcern","cpsf:Networkability").
input("cpsf:Boundaries","cpsf:includesConcern","cpsf:Behavioral").
input("cpsf:Boundaries","rdf:type","cpsf:Aspect").
input("cpsf:Boundaries","rdf:type","owl:NamedIndividual").
input("cpsf:c0003_01","cpsf:conditionProperty","cpsf:Input1ConsistentReadingFreq").
input("cpsf:c0003_01","cpsf:conditionPolarity","cpsf:positive").
input("cpsf:c0003_01","rdf:type","cpsf:Condition").
input("cpsf:c0003_01","rdf:type","owl:NamedIndividual").
input("cpsf:Responsibility","rdf:type","cpsf:Concern").
input("cpsf:Responsibility","rdf:type","owl:NamedIndividual").
input("cpsf:bc1","cpsf:refinedInto","cpsf:uc2").
input("cpsf:bc1","cpsf:refinedInto","cpsf:uc1").
input("cpsf:bc1","rdf:type","cpsf:BusinessCase").
input("cpsf:bc1","rdf:type","owl:NamedIndividual").
input("cpsf:Granularity","rdf:type","cpsf:Concern").
input("cpsf:Granularity","rdf:type","owl:NamedIndividual").
input("cpsf:AssuranceFacet","rdfs:comment","CPS-independent").
input("cpsf:AssuranceFacet","rdf:type","cpsf:Facet").
input("cpsf:AssuranceFacet","rdf:type","owl:NamedIndividual").
input("cpsf:Transformation","rdf:type","cpsf:Concern").
input("cpsf:Transformation","rdf:type","owl:NamedIndividual").
input("cpsf:SAMSecBoot","rdfs:comment","SAM uses secure boot").
input("cpsf:SAMSecBoot","cpsf:atomicStatement","sec_boot_sam").
input("cpsf:SAMSecBoot","cpsf:hasType","cpsf:PropertyType_Assertion").
input("cpsf:SAMSecBoot","rdf:type","cpsf:Property").
input("cpsf:SAMSecBoot","rdf:type","owl:NamedIndividual").
input("cpsf:Regulatory","rdf:type","cpsf:Concern").
input("cpsf:Regulatory","rdf:type","owl:NamedIndividual").
input("cpsf:Aspect","rdfs:comment","pg 15").
input("cpsf:Aspect","rdfs:comment","all instances are CPS-independent").
input("cpsf:Aspect","rdfs:subClassOf","cpsf:Concern").
input("cpsf:Aspect","rdf:type","owl:Class").
input("cpsf:Networkability","rdf:type","cpsf:Concern").
input("cpsf:Networkability","rdf:type","owl:NamedIndividual").
input("cpsf:Physical","rdf:type","cpsf:Concern").
input("cpsf:Physical","rdf:type","owl:NamedIndividual").
input("cpsf:nextFC","rdfs:comment","next level of functional decomposition").
input("cpsf:nextFC","rdfs:range","cpsf:Function").
input("cpsf:nextFC","rdfs:domain","cpsf:Function").
input("cpsf:nextFC","rdf:type","owl:ObjectProperty").
input("cpsf:Adaptability","rdf:type","cpsf:Concern").
input("cpsf:Adaptability","rdf:type","owl:NamedIndividual").
input("cpsf:UseCase","cpsf:nextFC","cpsf:Scenario").
input("cpsf:UseCase","rdf:type","cpsf:UseCase").
input("cpsf:UseCase","rdf:type","owl:NamedIndividual").
input("cpsf:UseCase","rdfs:subClassOf","cpsf:Function").
input("cpsf:UseCase","rdf:type","owl:Class").
input("cpsf:Identity","cpsf:includesConcern","cpsf:Verification").
input("cpsf:Identity","cpsf:includesConcern","cpsf:ResourceIdentification").
input("cpsf:Identity","cpsf:includesConcern","cpsf:Provenance").
input("cpsf:Identity","cpsf:includesConcern","cpsf:DataIntegrity").
input("cpsf:Identity","cpsf:includesConcern","cpsf:Configuration").
input("cpsf:Identity","cpsf:includesConcern","cpsf:Authorization").
input("cpsf:Identity","cpsf:includesConcern","cpsf:Authentication").
input("cpsf:Identity","rdf:type","cpsf:Concern").
input("cpsf:Identity","rdf:type","owl:NamedIndividual").
input("cpsf:Data","cpsf:includesConcern","cpsf:Velocity").
input("cpsf:Data","cpsf:includesConcern","cpsf:RelationshipBetweenData").
input("cpsf:Data","cpsf:includesConcern","cpsf:OperationsOnData").
input("cpsf:Data","cpsf:includesConcern","cpsf:Identity").
input("cpsf:Data","cpsf:includesConcern","cpsf:DataSemantics").
input("cpsf:Data","rdf:type","cpsf:Aspect").
input("cpsf:Data","rdf:type","owl:NamedIndividual").
input("cpsf:DataIntegrity","rdf:type","cpsf:Concern").
input("cpsf:DataIntegrity","rdf:type","owl:NamedIndividual").
input("cpsf:Condition","rdfs:subClassOf","cpsf:ImpactRuleConcepts").
input("cpsf:Condition","rdf:type","owl:Class").
input("cpsf:Constructivity","rdf:type","cpsf:Concern").
input("cpsf:Constructivity","rdf:type","owl:NamedIndividual").
input("cpsf:Storage","rdf:type","cpsf:Concern").
input("cpsf:Storage","rdf:type","owl:NamedIndividual").
% ======== SIMPLE EXAMPLE 1 ========
%       -- to be used together with theory*.lp
%          and with step1-{optimistic,skeptical,pessimistic}.lp
%
% SYSTEM DESCRIPTION
% Input device 1 can operate in one of slow-mode and fast-mode.
% The SAM determines the mode of operation of input device 1.
% Normally, input device 1 reads inputs with a consistent frequency.
% If the basic type of input device 1 is configured to use
% encrypted memory and fast-mode, then the device will be
% unable to maintain a consistent frequency of reading.
%
% CONFIGURATION
% The SAM and input device 1 are configured to use encrypted 
% memory and secure boot. 
% The basic type of input device 1 is used.
% The SAM is configured to set input device 1 to slow-mode.
%
% Questions:
%   1. Is the functionality concern satisfied?
%   2. Is the functional aspect satisfied?
%   3. Are all aspects satisfied?
% 
% Answers:
%   1. Yes
%   2. Yes (because all concerns and sub-concerns of functional aspect are satisfied)
%   3. Yes (because all aspects are satisfied)




% ------ Initial state of the CPS ------

% Properties
% ---Observations
obs(sat("encrypted_mem_input1"),true).
obs(sat("encrypted_mem_sam"),true).
obs(sat("sec_boot_input1"),true).
obs(sat("sec_boot_sam"),true).
obs(sat("slow_mode_input1"),true).

% Extra-framework configuration
config_feature("using_basic_input1").
%%%%descr("using_basic_input1","Basic type of input device 1 is in use").
% the basic type of input device 1 is used, unless we decide otherwise
%assumed("using_basic_input1",true).
obs(sat("using_basic_input1"),true).

step(0).

% TO BE CHANGED IN ONTOLOGY <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 
% --- not needed ---
% Must rename cpsf:addressedByProperty to cpsf:addresses and invert arguments
%input(P,"cpsf:addresses",C) :- input(C,"cpsf:addressedByProperty",P).

% TO BE CHANGED IN ONTOLOGY <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 
% --- not needed ---
%% Must populate cpsf:addressesAtFunc -- set to bc1 by default
%other_func(P,C,"cpsf:bc1") :-
%	input(P,"cpsf:addressesAtFunc",F), 
%	input(C,"cpsf:addressedByProperty",P),
%	F != "cpsf:bc1".
%input(P,"cpsf:addressesAtFunc","cpsf:bc1") :- 
%	input(C,"cpsf:addressedByProperty",P),
%	not other_func(P,C,"cpsf:bc1").

% impacts of requirements -- shortcut using addresses/3, from cpsf:addressedByProperty and cpsf:addressesAtFunc
%holds(impacted(C,F,pos),S) :-
%	step(S),
%	addresses(A,C,F),
%	holds(sat(A),S).



% ------ Constraints ------

%   Normally, input device 1 reads inputs with a consistent frequency.
fluent(sat("consist_reading_freq_input1")).
defined(neg,sat("consist_reading_freq_input1")).
%assumed("consist_reading_freq_input1",true).

%   An exception to this general rule is that, when the basic type 
%   of input 1 device is in use, using encrypted memory and 
%   fast mode impacts negatively the maintainability of a consistent 
%   reading frequency"
impacted(neg,sat("consist_reading_freq_input1"),S) :-
	step(S),
	holds(sat("using_basic_input1"),S),
	holds(sat("encrypted_mem_input1"),S),
	-holds(sat("slow_mode_input1"),S).
%%%%% NOTE: to use inference on the satisfaction of concerns,
%%%%%       one MUST define one of the following facts:
%%%%%
%%%%%         inference(concerns,pessimistic)
%%%%%         inference(concerns,skeptical)
%%%%%         inference(concerns,optimistic)


% ------ Input Interface ------

property(P) :- input(P,"rdf:type","cpsf:Property").
descr(P,D) :- input(P,"rdfs:comment",D).
atomic_statement(P,A) :- input(P,"cpsf:atomicStatement",A).
isAssertion(P) :- input(P,"cpsf:hasType","cpsf:PropertyType_Assertion").
concern(C) :- input(C,"rdf:type","cpsf:Concern").
aspect(A) :- input(A,"rdf:type","cpsf:Aspect").
subconcern(S,O) :- input(S,"cpsf:includesConcern",O).

% every aspect is a concern
concern(A) :- aspect(A).

% meta-aspect "all", which is a parent of every aspect
concern(all).
subconcern(all,A) :-
	aspect(A).

% TO BE CHANGED IN ONTOLOGY <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 
% --- not needed ---
%%addressedBy(C,P) :- input(C,"cpsf:addressedByProperty",P).
%addresses(A,C,F) :- 
%	input(P,"cpsf:addresses",C),
%	input(P,"cpsf:addressesAtFunc",F),
%	atomic_statement(P,A),
%	isAssertion(P).
	


nextFC(F1,F2) :- input(F2,"cpsf:nextFC",F1).
% Auxiliary relation isFunctionClass
isFunctionClass(F1) :- nextFC(F1,F2).
isFunctionClass(F2) :- nextFC(F1,F2).
functionClass(F,FC) :- isFunctionClass(FC), input(F,"rdf:type",FC).
refinedInto(F1,F2) :- input(F1,"cpsf:refinedInto",F2).
hasBC(APP,BC) :- input(APP,"cpsf:hasBC",BC).
relevantToFunc(C,F) :- input(C,"cpsf:relevantToFunc",F).

% a concern is relevant to F if a sub-concern is relevant to F  
relevantToFunc(C1,F) :- relevantToFunc(C2,F), subconcern(C1,C2).


-isAssertion(P) :- property(P), not isAssertion(P).

% Identify the last step in the input
last_step(S) :-
	step(S),
	S2=S+1,
	not step(S2).

rule(R) :- input(R,"cpsf:addressesConcern",C).
addressesAtFunc(R,F) :- input(R,"cpsf:addressesAtFunc",F).
addressesConcern(R,C) :- input(R,"cpsf:addressesConcern",C).
addressesPolarity(R,P) :- input(R,"cpsf:addressesPolarity",PO), asp_polarity(PO,P).
%
hasCondition(R,C) :- input(R,"cpsf:hasCondition",C).
conditionProperty(C,A) :- input(C,"cpsf:conditionProperty",P), atomic_statement(P,A).
conditionPolarity(C,P) :- input(C,"cpsf:conditionPolarity",PO), asp_polarity(PO,P).
asp_polarity("cpsf:positive",pos).
asp_polarity("cpsf:negative",neg).


% ------ Theory ------

% transitive closure of subconcern/2
tc(subconcern(C1,C2)) :- subconcern(C1,C2).
tc(subconcern(C1,C2)) :- subconcern(C1,C3), tc(subconcern(C3,C2)).

% transitive closure of subconcern/2, reflexive variant
tc0(subconcern(C,C)) :- concern(C).
tc0(subconcern(C1,C2)) :- tc(subconcern(C1,C2)).


% ---------------> Impact of requirements on concerns <---------------
% ASSUMPTION: satisfaction of concerns does not affect satisfaction of properties
addresses(Q,C,F) :-
	rule(Rule),
	addressesAtFunc(Rule,F),
	addressesConcern(Rule,C),
	hasCondition(Rule,Cond),
	conditionProperty(Cond,Q).


holds(impacted(C,F,M),S) :-
	step(S),
	rule(Rule),
	addressesAtFunc(Rule,F),
	addressesConcern(Rule,C),
	addressesPolarity(Rule,M),
	body_satisfied(Rule,S).

body_satisfied(Rule,S) :-
	step(S),
	rule(Rule),
	not -body_satisfied(Rule,S).

-body_satisfied(Rule,S) :-
	step(S),
	rule(Rule),
	hasCondition(Rule,Cond),
% ASSUMPTION: satisfaction of concerns does not affect satisfaction of properties
	-condSat(Cond,S).

% ASSUMPTION: satisfaction of concerns does not affect satisfaction of properties
-condSat(Cond,S) :-
	step(S),
	hasCondition(Rule,Cond),
	conditionProperty(Cond,A),
	conditionPolarity(Cond,pos),
	not holds(sat(A),S).

% ASSUMPTION: satisfaction of concerns does not affect satisfaction of properties
-condSat(A,S) :-
	step(S),
	hasCondition(Rule,Cond),
	conditionProperty(Cond,A),
	conditionPolarity(Cond,neg),
	not -holds(sat(A),S).


% DEBUGGING
%condSat(Cond,S) :-
%	step(S),
%	hasCondition(Rule,Cond),
%	conditionProperty(Cond,A),
%	conditionPolarity(Cond,pos),
%	not -holds(sat(A),S).
%condSat(A,S) :-
%	step(S),
%	hasCondition(Rule,Cond),
%	conditionProperty(Cond,A),
%	conditionPolarity(Cond,neg),
%	not holds(sat(A),S).


% The satisfaction of requirements is handled explicitly
% by user-provided state constraints
%-holds(sat_property(A),S) :-
%	step(S),
%	atomic_statement(P,A),
%	isAssertion(P),
%	not holds(A,S).
%
%-holds(sat(C),S) :-
%	step(S),
%	addresses(C,P),
%	atomic_statement(P,A), 
%	-holds(sat_property(A),S).

fluent(sat(A)) :- atomic_statement(P,A).
fluent(sat(A)) :- config_feature(A).
fluent(sat(C,F)) :- relevantToFunc(C,F).
impact_mode(pos). impact_mode(neg).
fluent(impacted(C,F,M)) :- concern(C), isFunctionClass(F), impact_mode(M).


% sat_sub(C,F) holds iff every relevant sub-concern of C is satisfied
%-holds(sat_sub(C1,F),S) :-
%	step(S), relevantToFunc(C1,F),
%	subconcern(C1,C2), relevantToFunc(C2,F),
%	not holds(sat(C2,F),S).
%fluent(sat_sub(C,F)) :- relevantToFunc(C,F).
%defined(neg,sat_sub(C,F)) :- relevantToFunc(C,F).

% The satisfaction of C in F is impacted by some combination of requirements at S
impacted(C,F,S) :-
	step(S), relevantToFunc(C,F),impact_mode(M),
	holds(impacted(C,F,M),S).

% Concern C has at least one relevant sub-concern in function F
has_relevant_subconcern(C1,F) :-
	subconcern(C1,C2), relevantToFunc(C2,F).

% A concern is positively influenced if:
% 1. a combination of requirements impacts it positively OR
% 2. a relevant sub-concern is satisfied
positively_influenced(C,F,S) :-
	step(S), relevantToFunc(C,F),
	holds(impacted(C,F,pos),S).
positively_influenced(C1,F,S) :-
	step(S), relevantToFunc(C1,F),
%	has_relevant_subconcern(C1,F),
%	holds(sat_sub(C1,F),S).
	subconcern(C1,C2), relevantToFunc(C2,F),
	holds(sat(C2,F),S).

% A concern is negatively influenced if:
% 1. a combination of requirements impacts it negatively OR
% 2. a relevant sub-concern is unsatisfied
negatively_influenced(C,F,S) :-
	step(S), relevantToFunc(C,F),
	holds(impacted(C,F,neg),S).
negatively_influenced(C1,F,S) :-
	step(S), relevantToFunc(C1,F),
%	has_relevant_subconcern(C1,F),
%	-holds(sat_sub(C1,F),S).
	subconcern(C1,C2), relevantToFunc(C2,F),
	-holds(sat(C2,F),S).

% A concern is affected by uncertain influence (from its sub-concerns) if:
% 1. a relevant sub-concern has unknown satisfaction
uncertainly_influenced(C1,F,S) :-
	step(S), relevantToFunc(C1,F),
%	has_relevant_subconcern(C1,F),
%	not holds(sat_sub(C1,F),S),
%	not -holds(sat_sub(C1,F),S).
	subconcern(C1,C2), relevantToFunc(C2,F),
	not holds(sat(C2,F),S),
	not -holds(sat(C2,F),S).


%%%%%%%% INFERENCE ON CONCERN SATISFACTION
%
% Select the type of inference with:
%
%   inference(concerns,pessimistic)
%   inference(concerns,skeptical)
%   inference(concerns,optimistic)
%

% PESSIMISTIC INFERENCE ON CONCERN SATISFACTION
% This is the simplest case, where concerns default to unsatisfied
% 
% A concern (in a given function f, e.g. use case u1) is satisfied if:
%   1. it is positively influenced AND
%   2. it is not negatively influenced
holds(sat(C,F),S) :-
	inference(concerns,pessimistic),
	step(S), relevantToFunc(C,F),
	positively_influenced(C,F,S),
	not negatively_influenced(C,F,S).

likelihood(sat(C,F),S,L) :-
	inference(concerns,pessimistic),
	step(S), relevantToFunc(C,F),
	positively_influenced(C,F,S),
	not negatively_influenced(C,F,S),
	likelihood_sat(C,F,S,L).
	%degree_impacted_pos(C,F,S,L).

% A concern is unsatisfied in all other cases.
defined(pos,sat(C,F)) :- inference(concerns,pessimistic), relevantToFunc(C,F). 

% SKEPTICAL INFERENCE ON CONCERN SATISFACTION
% This is a more advanced case, where the satisfaction status of a
% concern may remain unknown/undecided/uncertain
% 
% A concern (in a given function f, e.g. use case u1) is satisfied if:
%   1. it is positively influenced AND
%   2. it is not negatively influenced AND
%   3. is not affected by uncertain influence
holds(sat(C,F),S) :-
	inference(concerns,skeptical),
	step(S), relevantToFunc(C,F),
	positively_influenced(C,F,S),
	not negatively_influenced(C,F,S),
	not uncertainly_influenced(C,F,S).

likelihood(sat(C,F),S,D) :-
	inference(concerns,skeptical),
	step(S), relevantToFunc(C,F),
	positively_influenced(C,F,S),
	not negatively_influenced(C,F,S),
	not uncertainly_influenced(C,F,S),
	likelihood_sat(C,F,S,D).
	%degree_impacted_pos(C,F,S,D).

% A concern is unsatisfied if:
%   1. it is negatively influenced AND
%   2. it is not positively influenced AND
%   3. is not affected by uncertain influence
-holds(sat(C,F),S) :-
	inference(concerns,skeptical),
	step(S), relevantToFunc(C,F),
	negatively_influenced(C,F,S),
	not positively_influenced(C,F,S),
	not uncertainly_influenced(C,F,S).
% OR
%   1. it has no relevant sub-concerns AND
%   2. it is not positively influenced AND
%   3. it is not negatively influenced
-holds(sat(C,F),S) :-
	inference(concerns,skeptical),
	step(S), relevantToFunc(C,F),
	not has_relevant_subconcern(C,F),
	not positively_influenced(C,F,S),
	not negatively_influenced(C,F,S).


% The satisfaction status of a concern is unknown in all other cases.
% Implemented by making sat(C,F) inertial rather than defined


% OPTIMISTIC INFERENCE ON CONCERN SATISFACTION
% This is another simple case, where concerns default to unsatisfied,
% but concerns that have no requirements nor sub-concerns are vacuously
% satisfied.
% 
% A concern (in a given function f, e.g. use case u1) is satisfied if:
%   1. it is positively influenced AND
%   2. it is not negatively influenced
holds(sat(C,F),S) :-
	inference(concerns,optimistic),
	step(S), relevantToFunc(C,F),
	positively_influenced(C,F,S),
	not negatively_influenced(C,F,S).
likelihood(sat(C,F),S,D) :-
	inference(concerns,optimistic),
	step(S), relevantToFunc(C,F),
	positively_influenced(C,F,S),
	not negatively_influenced(C,F,S),
	likelihood_sat(C,F,S,D).
	%degree_impacted_pos(C,F,S,D).
% OR
%   1. it has no relevant sub-concerns AND
%   2. it is not positively influenced AND
%   3. it is not negatively influenced
holds(sat(C,F),S) :-
	inference(concerns,optimistic),
	step(S), relevantToFunc(C,F),
	not has_relevant_subconcern(C,F),
	not positively_influenced(C,F,S),
	not negatively_influenced(C,F,S).
likelihood(sat(C,F),S,D) :-
	inference(concerns,optimistic),
	step(S), relevantToFunc(C,F),
	not has_relevant_subconcern(C,F),
	not positively_influenced(C,F,S),
	not negatively_influenced(C,F,S),
	likelihood_sat(C,F,S,D).
	%degree_impacted_pos(C,F,S,D).

% A concern is unsatisfied in all other cases.
defined(pos,sat(C,F)) :- inference(concerns,optimistic), relevantToFunc(C,F). 


%%%% Relatedness of requirements across functions

% Definition. Requirement q1 is refined into requirement q2
% if they address the same concern in two functions F1 and F2
% and F1 is refined into F2.
refinedInto(Q1,Q2) :-
	addresses(Q1,C,F1),
	addresses(Q2,C,F2),
	refinedInto(F1,F2).

% Definition. Requirement q1 is related to requirement q2
% if there is a sequence r_1,...,r_k of requirements such that 
% q1 =r_1, q2=r_k, and every r_i is refined into r_i+1.
related(Q1,Q2) :-
	refinedInto(Q1,Q2),
	addresses(Q1,C,F1),	% make sure Q1, Q2 are requirements
	addresses(Q2,C,F2). % rather than functions

related(Q1,Q3) :-
	refinedInto(Q1,Q2),
	related(Q2,Q3).


%%%%%%%% OBSERVATIONS


% initial state of the CPS

holds(F,0) :-
	fluent(F),
	obs(F,true).

-holds(F,0) :-
	fluent(F),
	obs(F,false).

holds(F,0) :-
	fluent(F),
	assumed(F,true),
	not -holds(F,0).

-holds(F,0) :-
	fluent(F),
	assumed(F,false),
	not holds(F,0).

% Ad-hoc for prob_of_state functional fluent
holds(prob_of_state(100),0).

% next state: inertia axioms
is_defined(F) :- fluent(F), defined(M,F).

% NOTE: inertial for numerical fluents is defined on a case-by-case basis
-inertial(F) :- is_numerical(F).
-inertial(F) :- is_defined(F).

holds(F,S2) :-
	fluent(F),
	not -inertial(F),
	step(S), step(S2), S2=S+1,
	holds(F,S),
	not -holds(F,S2).

-holds(F,S2) :-
	fluent(F),
	not -inertial(F),
	step(S), step(S2), S2=S+1,
	-holds(F,S),
	not holds(F,S2).

holds(F,S) :-
	fluent(F),
	defined(neg,F),
	step(S),
	not -holds(F,S).

-holds(F,S) :-
	fluent(F),
	defined(pos,F),
	step(S),
	not holds(F,S).

% effect of a negative impact
-holds(A,S) :-
	impacted(neg,A,S).


% Ad-hoc treatment of prob_of_state functional fluent
holds(prob_of_state(P2),S2) :-
	step(S), step(S2), S2=S+1,
	holds(prob_of_state(P),S),
	do(A,S),
	prob_success(A,PSucc),
	P2a=P*PSucc,
	P2=P2a/100.

-unk_prob_success(S) :-
	step(S),
	do(A,S), prob_success(A,PSucc).
unk_prob_success(S) :-
	step(S),
	not -unk_prob_success(S).

holds(prob_of_state(P),S2) :-
	step(S), step(S2), S2=S+1,
	holds(prob_of_state(P),S),
	unk_prob_success(S).
%       -- to be used together with theory*.lp
%          and with step1-BASE.lp

% Reason skeptically about concerns, i.e. concerns default to unsatisfied
% but in case of contradictory impacts, from either sub-concerns or
% requirements, the reasoner concludes that the satisfaction of the
% concern is unknown.
%

% For illustration purposes, we consider as relevant only the following concerns
% and their ancestors:
%  * Confidentiality
%  * Functionality
%  * Integrity
%  * ComponentInventory
%
% The ComponentInventory concern is impacted negatively by the requirement to
% use the basic type of the input1 device and impacted positively by
% the requirement to use secure boot on the SAM. (These statements are for 
% illustration only and are not intended to represent any realistic system.)
%
% The example shows that, under this reasoning mode, the (relevant portion of the)
% trustworthiness tree is satisfied. That is due to the fact that the three
% above concerns are addressed by requirements that are satisfied.
% However, it is unknown whether the ComponentInventory is satisfied, due
% to the fact that it is impacted both positively and negatively by requirements.
% The uncertainty is propagated to the ancestors of ComponentInventory: Maintainability
% and Lifecycle.
%

% impact rules -- written in ASP for now since using_basic_input1 is
% a configuration rather than a property and thus is outside of
% the ontology.
% The rule for sec_boot_sam could be encoded in the ontology,
% but we keep it here for uniformity of this example file.
holds(impacted("cpsf:ComponentInventory","cpsf:bc1",neg),S) :-
	step(S),
	holds(sat("using_basic_input1"),S).
holds(impacted("cpsf:ComponentInventory","cpsf:bc1",pos),S) :-
	step(S),
	holds(sat("sec_boot_sam"),S).


% Enable skeptical inference on concern satisfaction
inference(concerns,skeptical).


% ------ Output Interface ------

output(D,property,"-",S) :- last_step(S), holds(sat(A),S), atomic_statement(P,A), descr(P,D).
output(C,concern,F,S) :- last_step(S), holds(sat(C,F),S),concern(C),not aspect(C), C!=all.
output(C,aspect,F,S) :- last_step(S), holds(sat(C,F),S),aspect(C).
output("concern-tree",tree,F,S) :- last_step(S), holds(sat(all,F),S).

output(C,"concern/aspect (unk)",F,S) :- 
	inference(concerns,skeptical),
	last_step(S), concern(C), relevantToFunc(C,F), 
	not holds(sat(C,F),S),
	not holds(sat(C,F),S).

output_headings("satisfied concern/aspect/property","type","function","step").
% ------ Output Interface ------

descr("using_basic_input1","Basic type of input device 1 is in use").
event_descr(recipient_rejects,"recipient rejects input").
action_descr(patch(sam),"patch the SAM").
